### ISSUE TITLE
can get uv  texture   like PRNet ? 

### ISSUE THREAD

**Issue by kekedan** [Microsoft/Deep3DFaceReconstruction#1]
hi， the model can get uv texture like PRNet? thanks~

**Comment by YuDeng** [comment]
Hi, our model only provides per-vertex texture. It cannot get UV map like PRNet. But if you prefer a UV map representation, you can turn to https://github.com/anilbas/3DMMasSTN. They provide a UV map for full BFM model which can be used to generate UV map for our model as well.

**Comment by dzk9528** [comment]
I tried using part the code(8_generate_posmap_300WLP.py) in 3dface together with face_projection and z_buffer generated from your reconstrcution code with the same BFM_UV.mat in (https://github.com/anilbas/3DMMasSTN), however, the result has some error
![vd025_texture](https://user-images.githubusercontent.com/24198258/55596498-9d764800-56fd-11e9-880f-5a2521fc135d.png)

Is that means we need to redo the tutte embedding for parameterization?

**Comment by YuDeng** [comment]
> I tried using part the code(8_generate_posmap_300WLP.py) in 3dface together with face_projection and z_buffer generated from your reconstrcution code with the same BFM_UV.mat in (https://github.com/anilbas/3DMMasSTN), however, the result has some error
> 
> does it mean I need to redo the tutte embedding for parameterization?

We only use a part of vertices among all of the original BFM (35709/53490). So the raw BFM_UV.mat provided by 3DMMasSTN cannot work correctly in our case. I've uploaded a select_vertex_id.mat(index starts from 1) which records the vertex index we use in our experiment. You can find it in the ./BFM subfolder. 
Accordingly, you can generate a new BFM_UV.mat which fits our model.

**Comment by dzk9528** [comment]
> > I tried using part the code(8_generate_posmap_300WLP.py) in 3dface together with face_projection and z_buffer generated from your reconstrcution code with the same BFM_UV.mat in (https://github.com/anilbas/3DMMasSTN), however, the result has some error
> > does it mean I need to redo the tutte embedding for parameterization?
> 
> We only use a part of vertices among all of the original BFM (35709/53490). So the raw BFM_UV.mat provided by 3DMMasSTN cannot work correctly in our case. I've uploaded a select_vertex_id.mat(index starts from 1) which records the vertex index we use in our experiment. You can find it in the ./BFM subfolder.
> Accordingly, you can generate a new BFM_UV.mat which fits our model.

Thanks for the reply and it works! But maybe you can tell all the users that the triangle indexs start from 1.

**Comment by YuDeng** [comment]
> I tried using part the code(8_generate_posmap_300WLP.py) in 3dface together with face_projection and z_buffer generated from your reconstrcution code with the same BFM_UV.mat in (https://github.com/anilbas/3DMMasSTN), however, the result has some error
> does it mean I need to redo the tutte embedding for parameterization?
> 
> We only use a part of vertices among all of the original BFM (35709/53490). So the raw BFM_UV.mat provided by 3DMMasSTN cannot work correctly in our case. I've uploaded a select_vertex_id.mat(index starts from 1) which records the vertex index we use in our experiment. You can find it in the ./BFM subfolder.
> Accordingly, you can generate a new BFM_UV.mat which fits our model.
> 
> Thanks for the reply and it works! But maybe you can tell all the users that the triangle indexs start from 1.

You're welcome and thanks for the advise!

**Comment by vastyao** [comment]
@dzk9528 Can you tell me how you did it? I'm confused by this question. Thank you very much. how to transform thr BFM.mat for face3d and how to get the mat for the image which I want to input

**Comment by dzk9528** [comment]
I am not sure whether I can give you some information for my current project, but you can try to use the selected_id.mat and try to modify the code in 3DMMasSTN to **reselect** the information of BFM_UV.mat.

**Comment by vastyao** [comment]
Thank you for answering my questions. If I do this for BFM_UV.mat, can it work for face3d yet? I am worry about which the index can't match the genarate.m. is it ok? what's more, 8_generate_posmap_300WLP.py need the .mat for the information about the input image, how can I make it ?  Thank you for answering my questions again.  if it's convenient, I hope can get some idea from you.

**Comment by dzk9528** [comment]
face3d is just some lib for python to process 3d face data, so I guess it could be used. But no need to generate again, you just need select index.
For the second question, I suggest you read the 3DDFA paper(they have matlab code) or download 300W -LP to get the 3d face model for 300w.

By the way, I am not sure this topic should be discussed here. You can further have a open issue on 3dface or 3DMMasSTN, which the author of them may give you a better answer.

**Comment by vastyao** [comment]
Thank you very much. I am just you have successfullly done the thing which I want to do, so I am exciting~

**Comment by ReverseSystem001** [comment]
> I am not sure whether I can give you some information for my current project, but you can try to use the selected_id.mat and try to modify the code in 3DMMasSTN to **reselect** the information of BFM_UV.mat.



> > > I tried using part the code(8_generate_posmap_300WLP.py) in 3dface together with face_projection and z_buffer generated from your reconstrcution code with the same BFM_UV.mat in (https://github.com/anilbas/3DMMasSTN), however, the result has some error
> > > does it mean I need to redo the tutte embedding for parameterization?
> > 
> > 
> > We only use a part of vertices among all of the original BFM (35709/53490). So the raw BFM_UV.mat provided by 3DMMasSTN cannot work correctly in our case. I've uploaded a select_vertex_id.mat(index starts from 1) which records the vertex index we use in our experiment. You can find it in the ./BFM subfolder.
> > Accordingly, you can generate a new BFM_UV.mat which fits our model.
> 
> Thanks for the reply and it works! But maybe you can tell all the users that the triangle indexs start from 1.

Hi，Do you retrain the 3DMMasSTN  to get a new BFM_UV.mat (35709) file or just Just pick out 35709 points based on the select_vertex_id.mat from the raw BFM_UV.mat（53490）.
