### ISSUE TITLE
suppl. material

### ISSUE THREAD

**Issue by BigDataHa** [microsoft/Deep3DFaceReconstruction#10]
where is Supplementary materials mentioned in the article

**Comment by yuefurong97** [comment]
同问，想看附加材料

**Comment by yuefurong97** [comment]
I have the same question with you.

**Comment by Ivy147** [comment]
I can't find the supplement,too.Can you tell me where I can download it?

**Comment by YuDeng** [comment]
Hi, we will upload supplementary materials soon.

**Comment by xjcvip007** [comment]
@YuDeng, thanks for your amazing job and looking for your supplymentary material~

**Comment by YuDeng** [comment]
Hi, for the supplement, check http://jlyang.org/cvprw19_3dface_supmat.pdf.
