### ISSUE TITLE
Unable to open the output mesh object.

### ISSUE THREAD

**Issue by viraatsworld** [microsoft/Deep3DFaceReconstruction#100]
I have successfully compiled the demo.py and got the output including .meshobject and .mat object.
But I am not able to open these objects in meshlab. I am new, please guide me on how to handle these objects.
This is the error I am getting:

![error](https://user-images.githubusercontent.com/35368530/101020007-d41bfa00-3593-11eb-809d-fe8c6aef1259.png)

This is the output I get after successful compilation:
![output](https://user-images.githubusercontent.com/35368530/101020034-e0a05280-3593-11eb-81d9-48f66d73a29d.png)

**Comment by YuDeng** [comment]
Hi, there seems to be a bug in demo.py. Some output obj files have wrong names (._mesh.obj) that cannot be open by meshlab. The error has been fixed now. Sorry for that.
