### ISSUE TITLE
tensorflow.python.framework.errors_impl.NotFoundError: ./renderer/rasterize_triangles_kernel.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by htktwr95** [microsoft/Deep3DFaceReconstruction#101]
I have installed tensorflow == 1.12.0 and mesh-renderer == 1.13.0 but while training the model I am getting the issue that is as follow.

tensorflow.python.framework.errors_impl.NotFoundError: ./renderer/rasterize_triangles_kernel.so: cannot open shared object file: No such file or directory.

Your help would be highly appreciated.

**Comment by martintaraz** [comment]
Were you able to somehoe solve the issue?

**Comment by htktwr95** [comment]
Yes, you have to import mesh_renderer instead of renderer in
face_decoder.py.

**Comment by thas97** [comment]
Whne i Tried to run 
python demo.py 
I got a permission error like this.

`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/asus/Deep3DFaceReconstruction/renderer/mesh_renderer.py", line 25, in <module>
    from renderer import rasterize_triangles
  File "/home/asus/Deep3DFaceReconstruction/renderer/rasterize_triangles.py", line 30, in <module>
    rasterize_triangles_module = tf.load_op_library('./renderer/rasterize_triangles_kernel.so')
  File "/home/asus/deep3d/lib/python3.6/site-packages/tensorflow/python/framework/load_library.py", line 60, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: ./renderer/rasterize_triangles_kernel.so: cannot open shared object file: Permission denied`

 Try sudo python demo.py & idsudo doesn't work Try below.
 
 And, I solved the permission error using 
 psudo python demo.py 
 
 https://stackoverflow.com/questions/44726377/sudo-python-command-not-found

**Comment by luowei0701** [comment]
Has the problem been solved?
