### ISSUE TITLE
Precompiled file rasterize_triangles_kernel.so is too short

### ISSUE THREAD

**Issue by viraatsworld** [microsoft/Deep3DFaceReconstruction#103]
How to handle this error. Should I manually compile?

![Screenshot from 2020-12-13 21-19-29](https://user-images.githubusercontent.com/35368530/102016838-047c4900-3d89-11eb-8f86-1243ff5623f7.png)

**Comment by YuDeng** [comment]
Hi, did you put rasterize_triangles_kernel.so in the right position? And did you run the code under python3.6 and tf 1.12?

**Comment by viraatsworld** [comment]
Yes, I reinitialize my system, it's done now thank you!
