### ISSUE TITLE
CoarseData could not be downloaded

### ISSUE THREAD

**Issue by chensheng-code** [microsoft/Deep3DFaceReconstruction#106]
CoarseData could not be downloaded when setting up the test environment is this a drug download?

**Comment by YuDeng** [comment]
CoarseData links to a file on google drive. You have to make sure you have access to google first.

**Comment by chensheng-code** [comment]
ensorflow.python.framework.errors_impl.NotFoundError: ./renderer/rasterize_triangles_kernel.so: undefined symbol: _ZN10tensorflow12OpDefBuilder4AttrESs

Thank you for your reply. What is the reason for this error? Is there any requirement for CUDA version or GCC version?

**Comment by YuDeng** [comment]
Hi, currently our code can only be run on tensorflow 1.12 if you use the pre-compiled rasterize_triangles_kernel.so provided in the repository. If you want to use custom tensorflow version, you have to compile the tf_mesh_renderer by yourself following the instruction.

**Comment by hitxuhao** [comment]
> Hi, currently our code can only be run on tensorflow 1.12 if you use the pre-compiled rasterize_triangles_kernel.so provided in the repository. If you want to use custom tensorflow version, you have to compile the tf_mesh_renderer by yourself following the instruction.

i run on tensorflow 1.12 & use the pre-compiled rasterize_triangles_kernel.so ，but have the same error,why

**Comment by YuDeng** [comment]
> > Hi, currently our code can only be run on tensorflow 1.12 if you use the pre-compiled rasterize_triangles_kernel.so provided in the repository. If you want to use custom tensorflow version, you have to compile the tf_mesh_renderer by yourself following the instruction.
> 
> i run on tensorflow 1.12 & use the pre-compiled rasterize_triangles_kernel.so ，but have the same error,why

Hi, you can check #111 for a solution.
