### ISSUE TITLE
Training pipeline for multi-image 3D face reconstruction with shape aggregation

### ISSUE THREAD

**Issue by zhongtao93** [microsoft/Deep3DFaceReconstruction#114]
Hi, 

Thank you for sharing training code! However, it seems that no code about identity aggregation. Is it means that there is no help or little help for improving reconstruction performence, or there are some other reasons?

Looking forward to your reply.

**Comment by YuDeng** [comment]
The identity aggregation strategy does have some improvements upon naive average aggregation quantitatively. However, the improvement is not that significant in visual aspect. And it takes some efforts to clean up the multi-image training code and combine it with the single image pipeline. So we are not plan to upload the multi image code at current stage, but may release it in the future.

**Comment by zhongtao93** [comment]
OK, thank you sharing code again!
