### ISSUE TITLE
bazel test is not working in the command prompt

### ISSUE THREAD

**Issue by Iswarya05** [microsoft/Deep3DFaceReconstruction#115]
I am  unable to find the "rasterize_triangles_kernel.so file in my folder and also bazel test is not working unable to proceed further can you please  check and let me know.

**Comment by YuDeng** [comment]
Hi, could you post the error message of bazel test here?

**Comment by Ishve** [comment]
FAILED: Build did NOT complete successfully
//mesh_renderer:mesh_renderer_test                                    NO STATUS
//mesh_renderer:rasterize_triangles_test                              NO STATUS
//mesh_renderer/kernels:rasterize_triangles_impl_test                 NO STATUS

FAILED: Build did NOT complete successfully

**Comment by Ishve** [comment]
FAILED: Build did NOT complete successfully
//mesh_renderer:mesh_renderer_test                                    NO STATUS
//mesh_renderer:rasterize_triangles_test                              NO STATUS
//mesh_renderer/kernels:rasterize_triangles_impl_test                 NO STATUS

FAILED: Build did NOT complete successfully

**Comment by Ishve** [comment]
FAIL: //mesh_renderer:mesh_renderer_test (see /home/preksh/.cache/bazel/_bazel_preksh/887e388b830f4415bdb0c32c0787f49a/execroot/tf_mesh_renderer/bazel-out/k8-fastbuild/testlogs/mesh_renderer/mesh_renderer_test/test.log)
FAIL: //mesh_renderer:rasterize_triangles_test (see /home/preksh/.cache/bazel/_bazel_preksh/887e388b830f4415bdb0c32c0787f49a/execroot/tf_mesh_renderer/bazel-out/k8-fastbuild/testlogs/mesh_renderer/rasterize_triangles_test/test.log)
INFO: Elapsed time: 2.862s, Critical Path: 2.67s
INFO: 3 processes: 4 linux-sandbox.
INFO: Build completed, 2 tests FAILED, 3 total actions
//mesh_renderer/kernels:rasterize_triangles_impl_test           (cached) PASSED in 0.4s
//mesh_renderer:mesh_renderer_test                                       FAILED in 2.3s
  /home/preksh/.cache/bazel/_bazel_preksh/887e388b830f4415bdb0c32c0787f49a/execroot/tf_mesh_renderer/bazel-out/k8-fastbuild/testlogs/mesh_renderer/mesh_renderer_test/test.log
//mesh_renderer:rasterize_triangles_test                                 FAILED in 2.6s
  /home/preksh/.cache/bazel/_bazel_preksh/887e388b830f4415bdb0c32c0787f49a/execroot/tf_mesh_renderer/bazel-out/k8-fastbuild/testlogs/mesh_renderer/rasterize_triangles_test/test.log

Executed 2 out of 3 tests: 1 test passes and 2 fail locally.
INFO: Build completed, 2 tests FAILED, 3 total actions

**Comment by YuDeng** [comment]
If you pass the first test (kernels:rasterize_triangles_impl_test), the library should be able to use.  Similar to #117.

**Comment by yougusee** [comment]
> FAILED: Build did NOT complete successfully
> //mesh_renderer:mesh_renderer_test NO STATUS
> //mesh_renderer:rasterize_triangles_test NO STATUS
> //mesh_renderer/kernels:rasterize_triangles_impl_test NO STATUS
> 
> FAILED: Build did NOT complete successfully

well,I met the same problem with you, how can i fix it

**Comment by Ishve** [comment]
> > FAILED: Build did NOT complete successfully
> > //mesh_renderer:mesh_renderer_test NO STATUS
> > //mesh_renderer:rasterize_triangles_test NO STATUS
> > //mesh_renderer/kernels:rasterize_triangles_impl_test NO STATUS
> > FAILED: Build did NOT complete successfully
> 
> well,I met the same problem with you, how can i fix it

Hi, if you pass the first test (kernels:rasterize_triangles_impl_test), the library is ready to use. You can find rasterize_triangles_kernel.so following the instruction of our repository and run the demo code as well as the training code.
The following two failed tests seem to cause by incompatibility between different versions of tf_mesh_renderer.
