### ISSUE TITLE
failed to load new trained model

### ISSUE THREAD

**Issue by yunbiaolin** [microsoft/Deep3DFaceReconstruction#119]
i tried a quick train of this model, but  the new trained model file failed to be loaded, anyone meet this issue before?

python demo.py --use_pb 0 --pretrain_weights result/model_test/iter_0.ckpt.data-00000-of-00001

DataLossError (see above for traceback): Unable to open table file result/model_test/iter_0.ckpt.data-00000-of-00001: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
	 [[node save/RestoreV2 (defined at demo.py:37)  = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]

**Comment by YuDeng** [comment]
Hi, you should run --pretrain_weights result/model_test/iter_0.ckpt instead of --pretrain_weights result/model_test/iter_0.ckpt.data-00000-of-00001.

**Comment by yunbiaolin** [comment]
got it. thanks.
