### ISSUE TITLE
Unit conversion during the data loading

### ISSUE THREAD

**Issue by zhipeng-fan** [microsoft/Deep3DFaceReconstruction#12]
Hi, thanks for sharing this awesome work. Just got one question for the data loading code, it seems that you performed the unit conversion by dividing 1e5 for all the base and mean shape. I am wondering is it a normal practice to do that? Cause I see that the location of the vertex in 3dmm is usually large (in the order of 1e5), what is the unit for those coordinates in the 3dmm model?

**Comment by YuDeng** [comment]
Hi, the unit of 3dmm is μm and we use dm in our experiment. We conduct this conversion simply to be consistent with our previous experiments. It would be fine if you choose another unit or the original one in 3dmm.
