### ISSUE TITLE
Unable to Set -D_GLIBCXX_USE_CXX11_ABI=1

### ISSUE THREAD

**Issue by Ishve** [microsoft/Deep3DFaceReconstruction#122]
Can you please explain how and where to  "Set -D_GLIBCXX_USE_CXX11_ABI=1 in ./mesh_renderer/kernels/BUILD before the compilation" process.  Is it relevant i am unable to set the value.

**Comment by YuDeng** [comment]
You can just change it here:
https://github.com/google/tf_mesh_renderer/blob/ba27ea1798f6ee8d03ddbc52f42ab4241f9328bb/mesh_renderer/kernels/BUILD#L29

**Comment by Ishve** [comment]
Thank you, It's working now
