### ISSUE TITLE
How many neurons are there in the last fully-connected layer of R-Net?

### ISSUE THREAD

**Issue by havefunbb** [microsoft/Deep3DFaceReconstruction#13]
In the paper, you said "we use a ResNet-50 network [22] to regress these coefficients by modifying the last fully-connected layer to 239 neurons." , but when I debug your code, and I found the count of output coefficients of R-Net is 257 ? I think that's because the count of lighting coefficients, in your paper it should be 9, but in your code, it's 27. which is right?

**Comment by YuDeng** [comment]
Yes, we change lighting coefficients from 9 to 27 so that illumination can be colored light. We find that it is better than assuming a white scene light under some extreme cases, where textures have to compensate for light color and lead to strange results.

**Comment by havefunbb** [comment]
OK，thanks for your answer. And I got another question when I tried to generate the projection image by using rasterizer method you mentioned in your paper, and I found that some vertex's color (defined in face_color) may out of range 255, what should I do with this strange color?

**Comment by YuDeng** [comment]
We simply clip face colors within the range of 0 to 255. While training, we do the same procedure before sending reconstruction image to facenet for feature extraction.

**Comment by havefunbb** [comment]
Got it and thank you
