### ISSUE TITLE
About BFM_model_front.mat

### ISSUE THREAD

**Issue by CharlesNord** [microsoft/Deep3DFaceReconstruction#135]
Hi, could you please explain how do you process the original BFM model, i.e., 01_MorphableModel.mat to get the BFM_model_front.mat?

I found the 'meanshape' is just the shapeMU in original BFM model times 1e5,  how do you convert the 'ShapePC' to 'idBase' ?

**Comment by CharlesNord** [comment]
Sorry, I just found the function transferBFM09(). Solved.

**Comment by Barry-Liang** [comment]
Hi, could you please share the BFM_model_front.mat file with me by a share link? Actually, I want to use this file in another project. I will appreciate it if you can help me with that. Thanks in advance.

**Comment by CharlesNord** [comment]
https://drive.google.com/drive/folders/105WLX_gDnxfb-FkYgXlWxuTpf8YGErbj?usp=sharing

**Comment by CharlesNord** [comment]
> Hi, could you please share the BFM_model_front.mat file with me by a share link? Actually, I want to use this file in another project. I will appreciate it if you can help me with that. Thanks in advance.

https://drive.google.com/drive/folders/105WLX_gDnxfb-FkYgXlWxuTpf8YGErbj?usp=sharing

**Comment by 15458wew** [comment]
Hello, one of my questions has been resolved from your answer. But I haven't found Exp_Pca.bin in the downloaded Coarse_dataset. Can you share this with me? My email is 547785213@qq.com, thank you very much.

**Comment by theshahjee** [comment]
Hi, you can download the `BFM_model_front.mat` file from the following link:

[Download Link](https://drive.google.com/drive/folders/1o4t5YIw7w4cMUN4bgU9nPf6IyWVG1bEk)

Let me know if you need further assistance!
