### ISSUE TITLE
Why you choose to use 80 coefficients to get the shape? why not use more coefficients, like 100, 120?

### ISSUE THREAD

**Issue by havefunbb** [microsoft/Deep3DFaceReconstruction#14]

**Comment by havefunbb** [comment]
or 199?

**Comment by YuDeng** [comment]
Originally, we use 80 coefficients to be consistent with MoFA{https://arxiv.org/abs/1703.10580}. We also conduct experiments with more shape basis but find little improvement. So we decide to maintain 80 coefficients for shape. Thanks!

**Comment by havefunbb** [comment]
Got it ,and thank you very much!

**Comment by havefunbb** [comment]
I was so impressed by your weakly-supervised method, and I am trying to reproduct your paper(论文复现). I would really appreciate if you could give me any friendly advices.
