### ISSUE TITLE
About Exp_Pca.bin

### ISSUE THREAD

**Issue by 15458wew** [microsoft/Deep3DFaceReconstruction#141]
Hello, I haven't found Exp_Pca.bin in the downloaded Coarse_dataset. Can you share this with me? My email is 547785213@qq.com, thank you very much.

**Comment by YuDeng** [comment]
You can download it from here: https://drive.google.com/file/d/1bw5Xf8C12pWmcMhNEu6PtsYVZkVucEN6/view?usp=sharing

**Comment by 15458wew** [comment]
Hello, thank you for your reply to solve my problem. But I encountered another problem. I encountered the following error when running demo_new19.py using the directly compiled .so file and the version of tensorflow 1.12.





Can you give me some ideas to solve the problem？
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "microsoft/Deep3DFaceReconstruction"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月26日(星期五) 中午1:42
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [microsoft/Deep3DFaceReconstruction] About Exp_Pca.bin (#141)





 
You can download it from here: https://drive.google.com/file/d/1bw5Xf8C12pWmcMhNEu6PtsYVZkVucEN6/view?usp=sharing
