### ISSUE TITLE
Solution always symmetric?

### ISSUE THREAD

**Issue by Pythonsegmenter** [microsoft/Deep3DFaceReconstruction#146]
The output that I seem to get is always symmetric. Is it correct to state that the outputted face will always be symmetric?

**Comment by YuDeng** [comment]
Hi, this conclusion is not correct. In some cases the output faces might seem symmetric, but they are not strictly symmetric.

**Comment by Pythonsegmenter** [comment]
Thank you for the reply. The result seemed symmetric, but it is good to know that this is not the case.
