### ISSUE TITLE
About render 3d model questions

### ISSUE THREAD

**Issue by steventai0212** [microsoft/Deep3DFaceReconstruction#149]
Hi, I have a question. In your code it's easy to project a 3d face model with texture to 2d image. And I have no idea how to project a 3d face model without texture (the color may like gray) on 2d just like you show the result in readme file.

**Comment by steventai0212** [comment]
![image](https://user-images.githubusercontent.com/54788985/114309236-24dec900-9b19-11eb-9666-c8b5e75ee978.png)
like this

**Comment by YuDeng** [comment]
Well, you can set the face texture to a constant (e.g 128) in https://github.com/microsoft/Deep3DFaceReconstruction/blob/5b131a3e67597da67409486e20db50007f48427d/face_decoder.py#L45.

**Comment by steventai0212** [comment]
> Well, you can set the face texture to a constant (e.g 128) in
> 
> https://github.com/microsoft/Deep3DFaceReconstruction/blob/5b131a3e67597da67409486e20db50007f48427d/face_decoder.py#L45
> 
> .

Thanks, it solve my problem!
