### ISSUE TITLE
Scale and translation for z buffer

### ISSUE THREAD

**Issue by linyanhong** [microsoft/Deep3DFaceReconstruction#15]
Hi

What's the scale and translation value for z-buffer if I want to align the mesh to image? For x,y, the rasterization can be done according to the process_img in preprocess_img.py. I cannot find something similar for z value. Thank you.

**Comment by YuDeng** [comment]
Hi, z-buffer is only used for handling occlusions during rasterization. The global scale of z will not influence rasterization process.
