### ISSUE TITLE
Why minus 1 when converting image plane coordinates to 3D sapce coordinates?

### ISSUE THREAD

**Issue by JiSuanJiDaWang** [microsoft/Deep3DFaceReconstruction#154]
Hi , I couldn't understand why minus 1  in `lm = np.stack([lm[:,0],h0 - 1 - lm[:,1]], axis = 1)` in function `align_img(img,lm,lm3D)`.  From my points of view, its `lm = np.stack([lm[:,0],h0 - lm[:,1]], axis = 1)`.
Thanks.

**Comment by YuDeng** [comment]
Originally, I used h-1-lm[:,1] to ensure that the point with zero value correspond to the last pixel of the image. 
However, a more accurate way should neither be h-1-lm[:,1] nor h-lm[:,1], but h-0.5-lm[:,1].
Let's just consider the pixel (0,0) on the image. It is actually a box of length 1 which centered at (0.5,h-0.5). Therefore, we should really use h-0.5-lm[:,1] to transfer between landmark coordinates and pixel coordinates.
