### ISSUE TITLE
About the role of gamma loss

### ISSUE THREAD

**Issue by jasonjsonjackson** [microsoft/Deep3DFaceReconstruction#155]
Hi ! Thanks for sharing your great work. I could not understand the role of the gamma loss when using 3 channels illumination （polychromatic light）since you said from your work that the gamma loss is to ensure a nearly monochromatic light. I would really appreciate it if you could give me some information about it. Thanks.

**Comment by YuDeng** [comment]
Hi, in the original paper we directly set all 3 channels of lighting to be identical. 
Later we found that this setting would lead to some artifacts in face textures given input images with abnormal lightings. Therefore, we replace the monochromatic light setting with polychromatic light to alleviate this problem. But we still want the lighting to be nearly monochromatic to avoid its compensation for face texture. So we add the gamma loss to constrain it.

**Comment by jasonjsonjackson** [comment]
> Hi, in the original paper we directly set all 3 channels of light to be identical.
> Later we found that this setting would lead to some artifacts in face textures given input images with abnormal lightings. Therefore, we replace the monochromatic light setting with polychromatic light to alleviate this problem. But we still want the light to be nearly monochromatic to avoid its compensation for face texture. So we add the gamma loss to constrain it.

Thank you so much : )
