### ISSUE TITLE
Do the 68 landmarks index need minus 1?

### ISSUE THREAD

**Issue by havefunbb** [microsoft/Deep3DFaceReconstruction#16]
You have made a 'facemodel_info.mat' in folder 'BFM'. And it contains the 68 landmarks' index. In your .mat, it's 'keypoints'. If I want to use these keypoints, should I minus 1 before use just like what you did to 'tri'.

**Comment by YuDeng** [comment]
Yes. Keypoints index stored in facemodel_info.mat starts from 1.  So it is necessary to minus them with 1 before using.

**Comment by havefunbb** [comment]
Got it and thank you
