### ISSUE TITLE
Question about the scale of the training dataset

### ISSUE THREAD

**Issue by YokkaBear** [microsoft/Deep3DFaceReconstruction#160]
Hi @YuDeng , thank you for your excellent work and open-source code.
I intend to train R-Net from scratch using a new dataset composed of ~200k images, and currently I am under the data preprocessing step. Noticing that the script preprocessing_img.py takes a relatively long time to run over my dataset, I wonder if decreasing the scale of the training dataset, e.g. down to ~50k, would work and achieve an acceptable experimental result or not. Looking forward to your reply, thanks a lot.

**Comment by YuDeng** [comment]
Hi, for image pre-processing, most of the time is cost by data IO. It is possible to reduce its time if it is combined into the dataloader part to avoid saving processed images to the hard disk.

We have tried to use dataset with around 70K images to train the model, e.g FFHQ. The performance of the model may drop slighting, but it still give reasonable result.

**Comment by YokkaBear** [comment]
Clearer sight now, thank you for your quick response.
