### ISSUE TITLE
When training R-Net, should the input image minus 'pixel_mean'?

### ISSUE THREAD

**Issue by havefunbb** [microsoft/Deep3DFaceReconstruction#17]

**Comment by YuDeng** [comment]
We did not do any preprocessing for input images. All input image used to train R-Net have intensities range from 0-255, in BGR order.

**Comment by havefunbb** [comment]
Ok, but in many image process cases, the image will minus the 'pixel_mean' before sending to CNN, so have you tried this kind of process?

**Comment by YuDeng** [comment]
We did not try this preprocessing step in our experiments. Actually, I think minus it with pixel_mean is not necessary because network can learn this bias by itself.

**Comment by havefunbb** [comment]
Ok, well, I would like to have a try. Thank you.
