### ISSUE TITLE
When will you release the pytorch code?

### ISSUE THREAD

**Issue by tsoydari** [microsoft/Deep3DFaceReconstruction#171]
Thanks a lot for the repo! This is impressive. But tensorflow 1 is very sad. When will you release the pytorch code?

**Comment by YuDeng** [comment]
Hi, the pytorch implementation is already cleaned up. It still needs some time for a open source review. We would be able to release the code within a week if everything goes well.

**Comment by ronslos** [comment]
Thanks for this wonderful work! I am eagerly waiting for the new pytorch implementation. Any news on a possible release date?

**Comment by YuDeng** [comment]
Hi, the review takes a longer time than I expected.  It may still need several days. We will release the code as soon as possible.

**Comment by sdulyq** [comment]
I am eagerly waiting for the new pytorch implementation now! Thanks for your comming release.

**Comment by YuDeng** [comment]
We have released the pytorch implementation now and I will close this issue.
