### ISSUE TITLE
Compile tf_mesh_renderer with TF 1.15

### ISSUE THREAD

**Issue by CengizhanYurdakul** [microsoft/Deep3DFaceReconstruction#177]
Hello, I am trying to implement 3D face reconstruction in another code running on Tensorflow 1.15. I'm in trouble with compiling tf_mesh_renderer. Is it possible to compile? If possible how can I do it? I am attaching the error I got.
![Screenshot from 2021-08-11 19-22-05](https://user-images.githubusercontent.com/53911245/129066344-ff663bff-0bbb-42b6-ac51-b5976ccda046.png)

**Comment by YuDeng** [comment]
Hi, the library can be used if you pass the first test out of three.  Did you successfully generate rasterize_triangles_kernel.so?

**Comment by CengizhanYurdakul** [comment]
If you want to generate rasterize_triangles_kernel.so clearly you need to create symbolic link on your tensorflow_core.

Firstly use 'find' command for sure that your path
```
find /home -name tensorflow_core
```
Secondly
```
cd <PATH THAT FOUND FROM FIND COMMAND>
cd /usr/local/lib/python3.6/dist-packages/tensorflow_core/
```
Finally create symbolic link
```
ln -s libtensorflow_framework.so.1 /usr/local/lib/python3.6/dist-packages/tensorflow_core/libtensorflow_framework.so
```
The problem is '.1' that end of the '.so'. Process can not reach this file and fail.

**Comment by xi4444x** [comment]
> Hello, I am trying to implement 3D face reconstruction in another code running on Tensorflow 1.15. I'm in trouble with compiling tf_mesh_renderer. Is it possible to compile? If possible how can I do it? I am attaching the error I got. ![Screenshot from 2021-08-11 19-22-05](https://user-images.githubusercontent.com/53911245/129066344-ff663bff-0bbb-42b6-ac51-b5976ccda046.png)

I'm just like you ,but I don't successfully generate the .so file.

**Comment by CengizhanYurdakul** [comment]
The main problem here is the name of the file `libtensorflow_framework.so`. After I created this file, I also created a symbolic link for `libtensorflow_framework.so.1` as in the command below. This solved my problem. Make sure you have your own path and try this.
```
ln -s /usr/local/lib/python3.6/dist-packages/tensorflow_core/libtensorflow_framework.so.1 /usr/local/lib/python3.6/dist-packages/tensorflow_core/libtensorflow_framework.so
```
