### ISSUE TITLE
Where can I find the pre-defiend skin region covering cheek,nose, and forehead?

### ISSUE THREAD

**Issue by havefunbb** [microsoft/Deep3DFaceReconstruction#18]
In the definition of loss texture, one of the regularization losses, you have mentioned a pre-defined skin region covering cheek, nose, and forehead. And you told readers to see suppl. material. Where can I get this pre-defined skin region?

**Comment by havefunbb** [comment]
Actually, maybe I found a spelling mistake in your paper. In section 4.3, "where R is a pre-defined skin region covering cheek, _**noise**_, and forehead"

**Comment by YuDeng** [comment]
Hi, thanks for the correction.  In the facemodel_info.mat, there is an element "skinmask", which is the skin region we used for training.
