### ISSUE TITLE
When computing landmark loss, should the coordinates/224? 

### ISSUE THREAD

**Issue by havefunbb** [microsoft/Deep3DFaceReconstruction#19]
When computing landmark loss, should the coordinates/224? If don't, the loss would be a very big number. And the same issue is that, when computing photometric loss, should RGB/255?

**Comment by YuDeng** [comment]
We divide image color with 255 before computing photometric loss. For landmark loss, we use image coordinates so landmarks are in a range from 0-224. We balance the weight between these two losses so landmark loss would not be too large.

**Comment by havefunbb** [comment]
Got it and thank you

**Comment by asterisk37n** [comment]
How about texture variance? Texture RGB are in [0, 255] or scaled into [0, 1] before computing variance?

**Comment by asterisk37n** [comment]
I found an answer that the range is [0, 1], thank you
https://github.com/microsoft/Deep3DFaceReconstruction/issues/27
