### ISSUE TITLE
How can I get the Expression Basis (which is inside "CoarseData.zip")?

### ISSUE THREAD

**Issue by yyssmm** [Microsoft/Deep3DFaceReconstruction#2]

**Comment by YuDeng** [comment]
Hi. We provide a link to the Expression Basis (provided by Juyong et al.) in the Prerequisite section. Follow the link and you can find CoarseData.zip in their Introduction part.

**Comment by yyssmm** [comment]
I am sorry, I have saw the link you talk about, but  Juyong et al. only provide the Basel Face Model, without the Expression Basis. Thank you!

**Comment by YuDeng** [comment]
You can download CoarseData here https://drive.google.com/uc?id=0B0A9UsiwtVTHY0p4em5qUzRISW8&export=download. Exp_Pca.bin should be inside.
