### ISSUE TITLE
How to render texture?

### ISSUE THREAD

**Issue by Edward-Lin** [microsoft/Deep3DFaceReconstruction#20]
Hey! I run your demo and the results are great!
But your demo only generates meshes without texture, and you mentioned in your readme file that you use tf_mesh_renderer as renderer during training and testing.
Could your kindly release some example code to show me how to render the results with tf_mesh_renderer, since there are not much documents about tf_mesh_renderer?
I'm just getting started with face reconstruction, appreciate your help!

**Comment by YuDeng** [comment]
Thanks for your interest in our work!
If you only need to generate reconstruction images as in our readme file, a simplest way is to use face_projection and z_buffer provided by reconstruction function in our demo. You can use them to do a rasterization to get reconstruction image. For implement of rasterization process, you can turn to rasterize_triangles_impl.cc in tf_mesh_renderer/mesh_renderer/kernels for a reference (https://github.com/google/tf_mesh_renderer/blob/master/mesh_renderer/kernels/rasterize_triangles_impl.cc).
If you want to achieve a backprop feature while training, I suggest using tf_mesh_renderer. Follow their instruction to compile it on Linux. Then, you can use mesh_renderer function defined in mesh_renderer.py to generate reconstruction image. For a better understanding, you can read their comments. 
Actually, tf_mesh_renderer has been through several major changes and we are using its old version. We have not revised our code to adapt to its latest version so we cannot provide you a clear example. Sorry for the inconvenience.

**Comment by YuDeng** [comment]
However, I can provide you with an example to show how we use mesh_renderer function in our training process. The code is only a reference and cannot be run directly. 

[render_example.zip](https://github.com/microsoft/Deep3DFaceReconstruction/files/3435256/render_example.zip)

**Comment by Edward-Lin** [comment]
Thanks again! I will try to figure it out with your example.

**Comment by Edward-Lin** [comment]
Hi, I have a new question about the rendering. You generate 27 parameters for lighting ("gamma" in https://github.com/microsoft/Deep3DFaceReconstruction/blob/80066b54507e98652e7efb2d4213146632380a05/reconstruct_mesh.py#L166) which corresponding to 3 lights, however, the tf-mesh-renderer's mesh_renderer function takes 6 parameters for each light (3 for light_position and 3 for light_intensities). So, I was wondering how to use your "gamma" for tf-mesh-renderer?
The Illumination_layer (https://github.com/microsoft/Deep3DFaceReconstruction/blob/80066b54507e98652e7efb2d4213146632380a05/reconstruct_mesh.py#L124) seems to generate vertices colors, but not rendered 2D image.

**Comment by YuDeng** [comment]
Hi, the function illumination_layer is used to calculate per-vertex color using face textures and diffuse reflection approximated by gamma.  Then, face color are sent to tf-mesh-renderer for rasterizations and rendering image. Since face color already contains lighting information, in this case, light_position and light_intensities used by tf-mesh-renderer can be ignored. The only usage of tf-mesh-render in my experiment is for rasterization. I set light_intensities parameter to zero so it would not affect face color.

**Comment by YuDeng** [comment]
Besides, 'gamma' cannot be directly used to tf-mesh-render. Because gamma represents the diffuse reflection of scene light instead of representing the light itself.

**Comment by munkim** [comment]
Building tf_mesh_renderer with bazel is a mess. The project repo doesn't take any Issues either. 
```
//mesh_renderer/kernels:rasterize_triangles_impl_test                    PASSED in 0.3s
//mesh_renderer:mesh_renderer_test                                       FAILED in 0.8s
//mesh_renderer:rasterize_triangles_test                                 FAILED in 0.8s
```
Is anyone also getting this error?

**Comment by Edward-Lin** [comment]
> Besides, 'gamma' cannot be directly used to tf-mesh-render. Because gamma represents the diffuse reflection of scene light instead of representing the light itself.

Thanks for your reply!

**Comment by Edward-Lin** [comment]
> Building tf_mesh_renderer with bazel is a mess. The project repo doesn't take any Issues either.
> 
> ```
> //mesh_renderer/kernels:rasterize_triangles_impl_test                    PASSED in 0.3s
> //mesh_renderer:mesh_renderer_test                                       FAILED in 0.8s
> //mesh_renderer:rasterize_triangles_test                                 FAILED in 0.8s
> ```
> 
> Is anyone also getting this error?

I install tf-mesh-renderer using "pip install mesh-renderer" directly. I've tested with tensorflow 1.9 version, and the higher version of tensorflow might work if you make some modifications to it's makefile. https://pypi.org/project/mesh-renderer/#files

**Comment by munkim** [comment]
Thank you for the reply. My problemwas an error I was able to compile it by following [this](https://github.com/google/sentencepiece/issues/293). 
But I am getting a new error: 
```
File "/home/mun/PROJECTS/ofried/model/3dmm/reconstruct_mesh.py", line 183, in render_face
    tf.cast(facemodel.face_buf-1,tf.int32),
AttributeError: 'BFM' object has no attribute 'face_buf'
```
How did you solve this issue?

**Comment by ZHUTAO142857** [comment]
> > Building tf_mesh_renderer with bazel is a mess. The project repo doesn't take any Issues either.
> > ```
> > //mesh_renderer/kernels:rasterize_triangles_impl_test                    PASSED in 0.3s
> > //mesh_renderer:mesh_renderer_test                                       FAILED in 0.8s
> > //mesh_renderer:rasterize_triangles_test                                 FAILED in 0.8s
> > ```
> > 
> > 
> > Is anyone also getting this error?
> 
> I install tf-mesh-renderer using "pip install mesh-renderer" directly. I've tested with tensorflow 1.9 version, and the higher version of tensorflow might work if you make some modifications to it's makefile. https://pypi.org/project/mesh-renderer/#files

Hi, I just tried the rendering function from https://github.com/YadiraF/face3d. However, I got a strange result that eye region can not be rendered. So I think that I may need to use tf_mesh_renderer. But I do not understand what is `face_norm`. Could you please tell me something about this param. It would be better if you can send me example code. My email is zhutao142857@foxmail.com

**Comment by Edward-Lin** [comment]
> > > Building tf_mesh_renderer with bazel is a mess. The project repo doesn't take any Issues either.
> > > ```
> > > //mesh_renderer/kernels:rasterize_triangles_impl_test                    PASSED in 0.3s
> > > //mesh_renderer:mesh_renderer_test                                       FAILED in 0.8s
> > > //mesh_renderer:rasterize_triangles_test                                 FAILED in 0.8s
> > > ```
> > > 
> > > 
> > > Is anyone also getting this error?
> > 
> > 
> > I install tf-mesh-renderer using "pip install mesh-renderer" directly. I've tested with tensorflow 1.9 version, and the higher version of tensorflow might work if you make some modifications to it's makefile. https://pypi.org/project/mesh-renderer/#files
> 
> Hi, I just tried the rendering function from https://github.com/YadiraF/face3d. However, I got a strange result that eye region can not be rendered. So I think that I may need to use tf_mesh_renderer. But I do not understand what is `face_norm`. Could you please tell me something about this param. It would be better if you can send me example code. My email is [zhutao142857@foxmail.com](mailto:zhutao142857@foxmail.com)

face_norm is the normal of vertices, you can simply set "face_norm = tf.nn.l2_normalize(face_shape)" if it is not provided. You can refer to: https://github.com/google/tf_mesh_renderer/blob/4dbf2947f0640b117ef9a505f60c617d07a52d7f/mesh_renderer/mesh_renderer_test.py#L43

**Comment by ZHUTAO142857** [comment]
> face_norm = tf.nn.l2_normalize(face_shape)

`
                # reconstruct 3D face with output coefficients and face model
                # facemodel = BFM()
                face_shape,face_texture,face_color,tri,face_projection,z_buffer,landmarks_2d = Reconstruction(coef,facemodel)
                face_norm = tf.nn.l2_normalize(face_shape)
                shape = np.squeeze(face_shape, (0))
                Render_layer(shape, face_norm, face_color, facemodel, 1)
                # ===========================
`
This is my code.
And it utrns out an error.
`    n_vex = int(facemodel.idBase.shape[0].value/3)
AttributeError: 'int' object has no attribute 'value'
`
您是计院的吗，我在浙大，读研一emmmm

**Comment by ZHUTAO142857** [comment]
This is my code
                # reconstruct 3D face with output coefficients and face model
                # facemodel = BFM()
                face_shape,face_texture,face_color,tri,face_projection,z_buffer,landmarks_2d = Reconstruction(coef,facemodel)
                face_norm = tf.nn.l2_normalize(face_shape)
                shape = np.squeeze(face_shape, (0))
                Render_layer(shape, face_norm, face_color, facemodel, 1)
                # ===========================
And it turns out an error
    n_vex = int(facemodel.idBase.shape[0].value/3)
AttributeError: 'int' object has no attribute 'value'
您是浙大计院的吗？我在浙大软院读研一^_^

**Comment by ZHUTAO142857** [comment]
> > > > Building tf_mesh_renderer with bazel is a mess. The project repo doesn't take any Issues either.
> > > > ```
> > > > //mesh_renderer/kernels:rasterize_triangles_impl_test                    PASSED in 0.3s
> > > > //mesh_renderer:mesh_renderer_test                                       FAILED in 0.8s
> > > > //mesh_renderer:rasterize_triangles_test                                 FAILED in 0.8s
> > > > ```
> > > > 
> > > > 
> > > > Is anyone also getting this error?
> > > 
> > > 
> > > I install tf-mesh-renderer using "pip install mesh-renderer" directly. I've tested with tensorflow 1.9 version, and the higher version of tensorflow might work if you make some modifications to it's makefile. https://pypi.org/project/mesh-renderer/#files
> > 
> > 
> > Hi, I just tried the rendering function from https://github.com/YadiraF/face3d. However, I got a strange result that eye region can not be rendered. So I think that I may need to use tf_mesh_renderer. But I do not understand what is `face_norm`. Could you please tell me something about this param. It would be better if you can send me example code. My email is [zhutao142857@foxmail.com](mailto:zhutao142857@foxmail.com)
> 
> face_norm is the normal of vertices, you can simply set "face_norm = tf.nn.l2_normalize(face_shape)" if it is not provided. You can refer to: https://github.com/google/tf_mesh_renderer/blob/4dbf2947f0640b117ef9a505f60c617d07a52d7f/mesh_renderer/mesh_renderer_test.py#L43

可以加好友吗？我的qq是1136133473

**Comment by ZHUTAO142857** [comment]
> > Besides, 'gamma' cannot be directly used to tf-mesh-render. Because gamma represents the diffuse reflection of scene light instead of representing the light itself.
> 
> Thanks for your reply!

Sorry but, could you show me your code about render?

**Comment by Edward-Lin** [comment]
> This is my code
> face_shape,face_texture,face_color,tri,face_projection,z_buffer,landmarks_2d = Reconstruction(coef,facemodel)
> face_norm = tf.nn.l2_normalize(face_shape)
> shape = np.squeeze(face_shape, (0))
> Render_layer(shape, face_norm, face_color, facemodel, 1)
> And it turns out an error
> n_vex = int(facemodel.idBase.shape[0].value/3)
> AttributeError: 'int' object has no attribute 'value'
> 您是浙大计院的吗？我在浙大软院读研一^_^

n_vex is the number of vertices, you can replace this line with:
`n_vex = int(facemodel.idBase.shape[0] / 3)`

**Comment by JungwooLee-ksm** [comment]
Does anyone have error like this when using tf_mesh_renderer?

TypeError: Tensors in list passed to 'values' of 'ConcatV2' Op have types [float64, float32] that don't all match.
