### ISSUE TITLE
landmark

### ISSUE THREAD

**Issue by bensss20112011** [microsoft/Deep3DFaceReconstruction#22]
I have  a txt of 68 landmarks. But in program, it need five landmarks. How can I choose these five landmark?

**Comment by YuDeng** [comment]
Hi, five landmarks are two centers of eyes, tip of nose and two outer corners of mouth. The nose tip and mouth corners can be directly obtained from 68 landmarks. And two centers of eyes can be derived using an average among landmarks around each eye.

**Comment by bensss20112011** [comment]
I want to ask the best way to render the texture

**Comment by YuDeng** [comment]
We do not provide a direct render function. But you can turn to #20 for some advice. Thanks.

**Comment by bensss20112011** [comment]
thank you!!

**Comment by Timmate** [comment]
Hi, I wrote a Colab Notebook that performs the detection of these 5 landmarks using the [face_alignment](https://github.com/1adrianb/face-alignment) library and also plots them on a given image so you can check how accurately they were aligned. The resulting landmarks are then written to a text file. Here is the link to the Notebook: https://colab.research.google.com/drive/1QfrswQuPDr6tlGxemhhIpd_awh_5M8a2?usp=sharing

**Comment by zeta7337** [comment]
> Hi, I wrote a Colab Notebook that performs the detection of these 5 landmarks using the [face_alignment](https://github.com/1adrianb/face-alignment) library and also plots them on a given image so you can check how accurately they were aligned. The resulting landmarks are then written to a text file. Here is the link to the Notebook: https://colab.research.google.com/drive/1QfrswQuPDr6tlGxemhhIpd_awh_5M8a2?usp=sharing. Hope that somebody will find it helpful.

hello,the file doesnt exist in you notebook

**Comment by Timmate** [comment]
> > Hi, I wrote a Colab Notebook that performs the detection of these 5 landmarks using the [face_alignment](https://github.com/1adrianb/face-alignment) library and also plots them on a given image so you can check how accurately they were aligned. The resulting landmarks are then written to a text file. Here is the link to the Notebook: https://colab.research.google.com/drive/1QfrswQuPDr6tlGxemhhIpd_awh_5M8a2?usp=sharing. Hope that somebody will find it helpful.
> 
> hello,the file doesnt exist in you notebook

Hi @zeta7337, thanks for pointing this out! I just updated my comment above and added a working link to that notebook
