### ISSUE TITLE
big error if input is not netural

### ISSUE THREAD

**Issue by ZHANG-SHI-CHANG** [microsoft/Deep3DFaceReconstruction#25]
netural:
![image](https://user-images.githubusercontent.com/30692249/62586663-1a564000-b8f1-11e9-86d2-98ac590dba2e.png)

no netural:
![image](https://user-images.githubusercontent.com/30692249/62586679-26da9880-b8f1-11e9-8660-17f6cc1ec7ec.png)

maybe i am a chinese?

**Comment by YuDeng** [comment]
Hi, this may because the camera distance of your photo is too small. Our training images have camera distances around 1 meter so it may not perform well in this case where camera distortion is significant.

**Comment by ZHANG-SHI-CHANG** [comment]
> Hi, this may because the camera distance of your photo is too small. Our training images have camera distances around 1 meter so it may not perform well in this case where camera distortion is significant.

thx~，i closed it
