### ISSUE TITLE
The details about your losses

### ISSUE THREAD

**Issue by havefunbb** [microsoft/Deep3DFaceReconstruction#26]
I just wanna make sure, when training R-Net, after 500k iters, what's the specific number of your losses?

**Comment by YuDeng** [comment]
Photo loss drops to 0.11 and id loss drops to 0.3 respectively. landmark loss is around 4 after an sqrt operation.

**Comment by havefunbb** [comment]
Does the landmark loss need sqrt operation? In your paper, it's a squared l2 loss.

**Comment by YuDeng** [comment]
Yes, we use a squared L2 loss for training. Square roots are only used for a visualization purpose.

**Comment by havefunbb** [comment]
Got it, thank you
