### ISSUE TITLE
How did you get the 35709 facial vertices from 53490 source model?

### ISSUE THREAD

**Issue by havefunbb** [microsoft/Deep3DFaceReconstruction#33]
I want to get a smaller face region from the 35709 facial vertices, where can I get some information about the index of  these vertices?

**Comment by YuDeng** [comment]
I use Meshlab to crop the face region I want from the original mesh and save it as a new obj. Then, I search the closest vertex on the original mesh for each vertex on the face region (the closest vertex should be itself). In this way, I can get the vertex index of these 35709 vertices.
