### ISSUE TITLE
PCA bases scaled with standard deviation

### ISSUE THREAD

**Issue by xinwen-cs** [microsoft/Deep3DFaceReconstruction#35]
Hi,
    I have a question that whether the idBase, exBase and texBase you provide are already scaled with their standard deviation respectively (as said in chapter 3 of your paper).

And I am inplementing Regularization in 4.3 of your paper, can you tell me the specific number（or order of magnitude) of ||alpha||^2, ||beta||^2 and ||delta||^2  when the training converged.

Thanks!

**Comment by YuDeng** [comment]
Hi, bases should be already scaled with std. The output magnitude of each coefficient should be ||alpha||^2 ~ 50, ||beta||^2 ~ 10, ||delta||^2~250.
