### ISSUE TITLE
How to get the 5 landmarks for my own image set?

### ISSUE THREAD

**Issue by SanyouWu** [microsoft/Deep3DFaceReconstruction#38]
Hi, thanks for your contribution.

And I have a question, in my own image set, how to get the 5 landmarks for every image?
(obtain by other face detect network like MTCNN??)

**Comment by rjadr** [comment]
For anybody seeking the answer, here is my solution using dlib:

`import dlib
import cv2
from imutils import face_utils

detector = dlib.get_frontal_face_detector()
predictor = dlib.shape_predictor('shape_predictor_68_face_landmarks.dat')

img_addr="YOUR_IMAGE.png"
img = cv2.imread(img_addr)

gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
rects = detector(gray, 0)

def midpoint(p1, p2):
    coords = (p1[0] + p2[0]) / 2, (p1[1] + p2[1]) / 2
    return [int(x) for x in coords]

if len(rects) > 0:
    for rect in rects:
        x = rect.left()
        y = rect.top()
        w = rect.right()
        h = rect.bottom()
        shape = predictor(gray, rect)
        shape_np = face_utils.shape_to_np(shape).tolist()
        left_eye = midpoint(shape_np[36], shape_np[39])
        right_eye = midpoint(shape_np[42], shape_np[45])
        features = [left_eye, right_eye, shape_np[33], shape_np[48], shape_np[54]]
        with open(img_addr.split('.')[0] + ".txt", "a") as f:
          for i in features:
            print(str(i[0]) + ' ' + str(i[1]), file=f)`
