### ISSUE TITLE
Question about angles through split coeff

### ISSUE THREAD

**Issue by SanyouWu** [microsoft/Deep3DFaceReconstruction#39]
Hi:

thanks for your contribution.

After split coeff, we can have ruler angle and use it to calculate rotation matrix.

I am confused that, is the angles equals to (roll, pitch, yaw)?

@

**Comment by YuDeng** [comment]
The angles returned represent the rotation along fixed axis (x,y,z) in the camera space. You can find a definition here https://en.wikipedia.org/wiki/Rotation_matrix. The General Rotations section clarifies the angles we use in our work.
