### ISSUE TITLE
do i need retrain the 3DMMSTN when i want to generate the BFM_UV.mat(35709)

### ISSUE THREAD

**Issue by ReverseSystem001** [microsoft/Deep3DFaceReconstruction#41]
Hi，Do you retrain the 3DMMasSTN to get a new BFM_UV.mat (35709) file or just pick out 35709 points based on the select_vertex_id.mat from the raw BFM_UV.mat（53490）.

**Comment by YuDeng** [comment]
We do not retrain 3DMMasSTN. We only pick out 35709 points from original BFM.

**Comment by ReverseSystem001** [comment]
thanks for your reply. but I have another question. that is : what is the difference between face_front_ids.Mat and the index file. why are they not the same.&nbsp;



---Original---
