### ISSUE TITLE
why select_vertex_id.mat and BFM_front_idx.mat are difference?

### ISSUE THREAD

**Issue by ReverseSystem001** [microsoft/Deep3DFaceReconstruction#42]
hi, thanks for sharing this code. when i read the function transferBFM09() in load_data.py.
the chosen indexes were based on BFM_front_idx.mat. why not use select_vertex_id.mat(35709, 1)??? and what is the difference between  select_vertex_id.mat and BFM_front_idx.mat(35709,1)

hopes for you reply!  thanks

**Comment by YuDeng** [comment]
Hi, select_vertex_id records vertex indexes in original BFM09 model(35709/53480),while BFM_front_idx records vertex indexes in the BFM model without inner mouth region(35709/53215).

**Comment by ReverseSystem001** [comment]
thanks for your reply.&nbsp; which index file（35709）do you use to pick out the indexes which was used for generate the BFM_UV. mat.&nbsp; hope your reply.&nbsp; thanks again.&nbsp;



---Original---

**Comment by jackspiderman** [comment]
> thanks for your reply.&nbsp; which index file（35709）do you use to pick out the indexes which was used for generate the BFM_UV. mat.&nbsp; hope your reply.&nbsp; thanks again.&nbsp;
> […](#)
> ---Original--- From: "YuDeng"<notifications@github.com&gt; Date: Tue, Oct 29, 2019 15:18 PM To: "microsoft/Deep3DFaceReconstruction"<Deep3DFaceReconstruction@noreply.github.com&gt;; Cc: "Author"<author@noreply.github.com&gt;;"reverseSystem"<892379162@qq.com&gt;; Subject: Re: [microsoft/Deep3DFaceReconstruction] why select_vertex_id.mat and BFM_front_idx.mat are difference? (#42) Hi, select_vertex_id records vertex indexes in original BFM09 model(35709/53480),while BFM_front_idx records vertex indexes in the BFM model without inner mouth region(35709/53215). — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

I get stuck in the same situation because I need BFM_UV coordinates to extract UV map from vertex coloured obj file generated from this project. Sadly, author doesn't give this list for us.  Anyone can guide me how to generate a BFM_UV from the obj, I would be really appreciate.

**Comment by jackspiderman** [comment]
I have solved this issue. BFM_UV can be gotten by using some tools such as 3dmax, uvlayout. But it should be careful to avoid overwriting pixels while rendering colors to uv texture file.

**Comment by ReverseSystem001** [comment]
可以写个博客，分享一下具体实现流程------------------ 原始邮件 ------------------
发件人: "zhouquan"<notifications@github.com>
发送时间: 2020年2月24日(星期一) 下午4:16
收件人: "microsoft/Deep3DFaceReconstruction"<Deep3DFaceReconstruction@noreply.github.com>;
抄送: "reverseSystem"<892379162@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [microsoft/Deep3DFaceReconstruction] why select_vertex_id.mat andBFM_front_idx.mat are difference? (#42)



I have solved this issue. BFM_UV can be gotten by using some tools such as 3dmax, uvlayout. But it should be careful to avoid overwriting pixels while rendering colors to uv texture file.
 
&mdash;
