### ISSUE TITLE
How to paste the rendered 2d image back to the original image

### ISSUE THREAD

**Issue by wtrnash** [microsoft/Deep3DFaceReconstruction#43]
Hello, thank you very much for sharing your code. I got the reconstructed result based on your code and got the image after the face rendering. How should I paste the rendered 2d image back to the original image?

**Comment by rsiddharth-clustrex** [comment]
Hi, How did you render the face?

**Comment by wtrnash** [comment]
> Hi, How did you render the face?

I refer to the render part of this code: https://github.com/YadiraF/face3d

**Comment by rsiddharth-clustrex** [comment]
use tf_mesh_renderer https://github.com/google/tf_mesh_renderer/tree/master/mesh_renderer

**Comment by Moon-W** [comment]
> Hello, thank you very much for sharing your code. I got the reconstructed result based on your code and got the image after the face rendering. How should I paste the rendered 2d image back to the original image?
你好，请问你实现了这个功能了吗，可以分享一下代码吗？谢谢！

**Comment by wtrnash** [comment]
> > Hello, thank you very much for sharing your code. I got the reconstructed result based on your code and got the image after the face rendering. How should I paste the rendered 2d image back to the original image?
> > 你好，请问你实现了这个功能了吗，可以分享一下代码吗？谢谢！

我是通过前处理的逆变换，依次分别对预处理的crop、resize、仿射变换进行逆变换然后实现了贴回原图，你可以试试。

**Comment by Moon-W** [comment]
> > > Hello, thank you very much for sharing your code. I got the reconstructed result based on your code and got the image after the face rendering. How should I paste the rendered 2d image back to the original image?
> > > 你好，请问你实现了这个功能了吗，可以分享一下代码吗？谢谢！
> 
> 我是通过前处理的逆变换，依次分别对预处理的crop、resize、仿射变换进行逆变换然后实现了贴回原图，你可以试试。

非常感谢你的回复，但我不太能理解这个过程，如果方便的话，请问你可以把代码贴一下或者发我的邮箱吗？万分感谢！！！
ChrisandPaul3@163.com

**Comment by ZHUTAO142857** [comment]
> > Hi, How did you render the face?
> 
> I refer to the render part of this code: https://github.com/YadiraF/face3d

请问你是怎么实现的呢？我用这个代码之后的结果是眼球部位没有渲染。
