### ISSUE TITLE
Artifacts on 2d rendered images

### ISSUE THREAD

**Issue by munkim** [microsoft/Deep3DFaceReconstruction#44]
Hi, I was able to follow #20 and render 2d image after reconstruction. But why does it create the blue-greenish artifacts on the image? 

![fg](https://user-images.githubusercontent.com/17050940/68316493-8f1f4e80-0087-11ea-873c-52dc0d9bdc19.png)

**Comment by munkim** [comment]
I think I found a solution in #13

**Comment by DragonZzzz** [comment]
Is it convenient for you to offer a example for me, because my render results is all 0 follow the authors' example. I'm debuging now.
![image](https://user-images.githubusercontent.com/22747238/68541834-4f39cd80-03df-11ea-83ed-8e3ab44dc6b7.png)

**Comment by munkim** [comment]
If you can provide a code, I can take a look.

**Comment by DragonZzzz** [comment]
I  check my code and visualize the results on different conditions. And I think it's caused by wrong normals(calculated by myself) or camera parameters . After rasterizer, the barycentric_coordinates are all 0, which makes the pixel value is background value(0). But I don't find the solution now.

**Comment by DragonZzzz** [comment]
@munkim  I have fixed this problem.My vertices are not in (-1,1). Thank you very much!

**Comment by JungwooLee-ksm** [comment]
> If you can provide a code, I can take a look.
> 
> But here is an example
> 
> ```
>     rendered = mesh_renderer.mesh_renderer(
>         face_shape,
>         tf.cast(facemodel.tri - 1, tf.int32),
>         face_norm,
>         face_color,
>         camera_position = camera_position,
>         camera_lookat = camera_lookat,
>         camera_up = camera_up,
>         light_positions = light_positions,
>         light_intensities = light_intensities,
>         image_width = width,
>         image_height = height,
>         fov_y = 12.5936,
>         ambient_color = ambient_color)
> 
>     with self.test_session() as sess:
>       images = sess.run(rendered, feed_dict={})
>       images = images[:, :, :, :-1] # Get RGB only
>       if sampling:
>         for i in range(images.shape[0]):
>           image = images[i]
>           result_bytes = sess.run(tf.image.encode_png(image))
>           with open(os.path.join(os.getcwd(), 'sample_%s.png' % i), 'wb') as output_file:
>               output_file.write(result_bytes)
> 
>     return images
> ```

Can I ask about your settings about rendering parameters?
        camera_position = camera_position,
        camera_lookat = camera_lookat,
        camera_up = camera_up,
        light_positions = light_positions,
        light_intensities = light_intensities,
        image_width = width,
        image_height = height,
        fov_y = 12.5936,
        ambient_color = ambient_color

I use setting like below(as author gave example):
	camera_position = tf.constant([0,0,10.0])
	camera_lookat = tf.constant([0,0,0.0])
	camera_up = tf.constant([0,1.0,0])
	light_positions = tf.tile(tf.reshape(tf.constant([0,0,1e5]),[1,1,3]),[batchsize,1,1])
	light_intensities = tf.tile(tf.reshape(tf.constant([0.0,0.0,0.0]),[1,1,3]),[batchsize,1,1])
	ambient_color = tf.tile(tf.reshape(tf.constant([1.0,1,1]),[1,3]),[batchsize,1])

and It gave me error like this:
TypeError: Tensors in list passed to 'values' of 'ConcatV2' Op have types [float64, float32] that don't all match.
