### ISSUE TITLE
Texture and Illumination coefficients

### ISSUE THREAD

**Issue by xinwen-cs** [microsoft/Deep3DFaceReconstruction#45]
Hi, Yu,
I am re-implementing this paper and I have finished the photometric loss, landmark loss and regularizations. I find that my network can not regress texture coef(delta) and easily regress illumination coef(gamma). In other word, when the network is fed with a black man, the network thinks that it is the scene illumination that too low not the raw face texture too dark.
I want to ask is this a normal phenomenon?
And are the results posted in your paper rendered with illumination or without illumination that the network estimated?
Thanks!

**Comment by Moon-W** [comment]
@xinwen-cs Hi，I have some trouble when I tried to reimplenment the photometric loss, could you give me some advice or share your loss function? Thanks a lot !

**Comment by YuDeng** [comment]
Hi, results in the paper are all rendered with illumination. It is true that face textures and illumination are sometimes entangled with each other so for black man the predicted illumination might be dark. We do not handle this problem in the paper so this problem might occurs in certain cases.

**Comment by xinwen-cs** [comment]
> @xinwen-cs Hi，I have some trouble when I tried to reimplenment the photometric loss, could you give me some advice or share your loss function? Thanks a lot !

Hi,I am struggling too. If you need help, you should describe the problem you met clearly and open an issue or e-mail the author. FYI, I just use MSE loss now(though not good enough).

**Comment by xingmimfl** [comment]
> Hi, Yu,
> I am re-implementing this paper and I have finished the photometric loss, landmark loss and regularizations. I find that my network can not regress texture coef(delta) and easily regress illumination coef(gamma). In other word, when the network is fed with a black man, the network thinks that it is the scene illumination that too low not the raw face texture too dark.
> I want to ask is this a normal phenomenon?
> And are the results posted in your paper rendered with illumination or without illumination that the network estimated?
> Thanks!

hello, have you re-implemented this paper?? I'm also trying to re-implement this paper, but imbalance of losses confused me
