### ISSUE TITLE
2D face alignment in preprocessing

### ISSUE THREAD

**Issue by hungsing92** [microsoft/Deep3DFaceReconstruction#46]
Hi,

Many thanks for your work!

I have a question that why you don't do rotation alignment in image preprocessing, and how can I do that at the same time the model can work properly. I didn't understand how the POS function work, if you can tell me that is better.

Best regards

**Comment by YuDeng** [comment]
Hi, the POS function solves a scale and translation between a standard 3D face shape and a face in the image. We do not handle rotations because we want the network to learn this factor as well. Thanks.
