### ISSUE TITLE
IndexError: too many indices for array

### ISSUE THREAD

**Issue by MarMus112** [microsoft/Deep3DFaceReconstruction#48]
when I suppose my image to demo.py ,this happens
`To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  k,_,_,_ = np.linalg.lstsq(A,b)
Traceback (most recent call last):
  File "demo.py", line 76, in <module>
    demo()
  File "demo.py", line 55, in demo
    input_img,lm_new,transform_params = Preprocess(img,lm,lm3D)
  File "C:\Users\Utente\Desktop\1x\Deep3DFaceReconstruction-master\preprocess_img.py", line 65, in Preprocess
    img_new,lm_new = process_img(img,lm,t,s)
  File "C:\Users\Utente\Desktop\1x\Deep3DFaceReconstruction-master\preprocess_img.py", line 46, in process_img
    img = img[:,:,::-1]
IndexError: too many indices for array
`
[matteo.txt](https://github.com/microsoft/Deep3DFaceReconstruction/files/3871375/matteo.txt)
this is the txt input file .

why returns this error?

**Comment by YuDeng** [comment]
The problem seems to be caused by the input image instead of matteo.txt you provide. Could you check the shape of image. It should be h*w*c.

**Comment by MarMus112** [comment]
Mhh... How can I do it?If my image isn't hwc How can I convert it?

**Comment by YuDeng** [comment]
What is the shape of your image? If it does not have channel dimension, e.g in shape hw, you can add a new dimension at last and copy it three times so the new image would be in a shape of h*w*3.

**Comment by MarMus112** [comment]
`>>> import numpy as np
>>> import cv2
>>> img=cv2.imread('matteo.png')
>>> h,w,c=img.shape
>>> print (h,w,c)
456 368 3`

**Comment by YuDeng** [comment]
This is strange. Did you run the demo successfully with the image provided in the repository?

**Comment by nodecomplete** [comment]
I had exactly this problem when running the demo.
The problem went away when I updated the version of Pillow from 3.1.2 to 4.1.0.
My version of numpy is 1.13.3.
