### ISSUE TITLE
Camera distance 10

### ISSUE THREAD

**Issue by havefunbb** [microsoft/Deep3DFaceReconstruction#49]
Projection is a very important procedure since you use 2d info to do weakly supervisation.  You set camera posion (0,0,10), and to get a suitable face image, you set fov 12.5936. Actually, it's not precise since each photo is taken at different distance. So, this may cause some shape error. What do you think about this issue, or do you have any solution like 'dynamic projection procedure'.

**Comment by havefunbb** [comment]
I have an idea that I can add an output neural in the full connect layer, and this output value means the distance between camera and face. With this value, we can calculate the fov, and then doing a dynamic projection on each pic. What do you think about this idea?

**Comment by hungsing92** [comment]
There is a translation parameter.
