### ISSUE TITLE
didn't succeed to run the demo

### ISSUE THREAD

**Issue by deuse79** [microsoft/Deep3DFaceReconstruction#5]
Hello everybody, so im brand new to python, but very motivated to make deep3Dface reconstruction work so i spent two days downloading and installing all the packages, cloning the repositery, installing everything and puting good files in good folders, and then asked myself how the program is running, should i replace the images in the input folder with one of mine ? i don't get it and feel a bit lost, so i ran the demo.py like that and got this message before the window close: 

2019-05-08 23:08:10.069653: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
reconstructing...
1
C:\Users\79\Desktop\neuron\Deep3DFaceReconstruction\Deep3DFaceReconstruction\preprocess_img.py:19: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  k,_,_,_ = np.linalg.lstsq(A,b)

then got another message but didnt had time to read or copy because windows closed directly.

any help is very welcome, thanks David

**Comment by deuse79** [comment]
this is what i got :/

C:\Users\79\Deep3DFaceReconstruction>demo.py
2019-05-08 23:25:05.281927: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
reconstructing...
1
C:\Users\79\Deep3DFaceReconstruction\preprocess_img.py:19: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  k,_,_,_ = np.linalg.lstsq(A,b)
Traceback (most recent call last):
  File "C:\Users\79\Deep3DFaceReconstruction\demo.py", line 76, in <module>
    demo()
  File "C:\Users\79\Deep3DFaceReconstruction\demo.py", line 64, in demo
    shape = np.squeeze(face_shape,[0])
  File "C:\Users\79\AppData\Local\Programs\Python\Python37\lib\site-packages\numpy\core\fromnumeric.py", line 1388, in squeeze
    return squeeze(axis=axis)
TypeError: 'list' object cannot be interpreted as an integer

**Comment by YuDeng** [comment]
Hi, this problem is due to the incompatibility of numpy versions. You can modify all [0] in np.squeeze functions to axis = 0. You can turn to https://github.com/microsoft/Deep3DFaceReconstruction/issues/4 .
Thanks!

**Comment by deuse79** [comment]
Thanks a lot Yu ! it really helped ! the demo worked fine at the end !
but i didn't suceed to install dlib and face detector then, but i find a way, finding the needed points
manually with photoshop :))), and guess what its a bit longer but i works too that way !

**Comment by YuDeng** [comment]
Glad to hear that it works. Hope it can help you with your work :)
