### ISSUE TITLE
Question about tf_mesh_render parameter fov_y and 2D projection parameter focal

### ISSUE THREAD

**Issue by hungsing92** [microsoft/Deep3DFaceReconstruction#50]
你好，

请问一下渲染时候使用的相机视角宽度系数fov_y和3d到2d投影时相机focal系数是怎么计算的？因为现在我打算使用[kaolin](https://github.com/NVIDIAGameWorks/kaolin/blob/master/examples/renderers/DIB-R/graphics/test/test_vc.py)替换tf_mesh_render, 发现使用tf_mesh_render的fov_y系数会导致渲染的结果只看到鼻子。所以我想知道fov_y 和 相机的focal系数之间的关系，如果有相关资料的话，烦请告诉我

祝好！

**Comment by mumuyanyan** [comment]
> 你好，
> 
> 请问一下渲染时候使用的相机视角宽度系数fov_y和3d到2d投影时相机focal系数是怎么计算的？因为现在我打算使用[kaolin](https://github.com/NVIDIAGameWorks/kaolin/blob/master/examples/renderers/DIB-R/graphics/test/test_vc.py)替换tf_mesh_render, 发现使用tf_mesh_render的fov_y系数会导致渲染的结果只看到鼻子。所以我想知道fov_y 和 相机的focal系数之间的关系，如果有相关资料的话，烦请告诉我
> 
> 祝好！

请问，找到答案了吗

**Comment by hungsing92** [comment]
fov_y: 12.5936, focal: 1015
可以搜索：镜头焦距与视场角计算方法
