### ISSUE TITLE
Rendered 2D reconstruction image seemed to be "cut" unexpectedly

### ISSUE THREAD

**Issue by MengXinChengXuYuan** [microsoft/Deep3DFaceReconstruction#52]
Hi I followed issue #20 and tried to render the constructed image back to the 2D face exactly by using the code below:
```
def Render_layer(face_shape, face_norm, face_color, angles, facemodel, size, batchsize):

	n_vex = int(facemodel.idBase.shape[0]/3)
	face_shape = tf.reshape(face_shape,[n_vex,3])
	face_norm = tf.reshape(face_norm,[n_vex,3])
	face_color = tf.reshape(face_color,[batchsize, n_vex,3])

	# euler_angles = tf.Variable(angles) # tf.contrib.eager.Variable(angles)
	model_rotation = mesh_renderer.camera_utils.euler_matrices(angles)[0, :3, :3]

	vertices_world_space = tf.reshape(
		tf.matmul(face_shape, model_rotation, transpose_b=True),
		[1, n_vex, 3])

	normals_world_space = tf.reshape(
		tf.matmul(face_norm, model_rotation, transpose_b=True),
		[1, n_vex, 3])

	camera_position = tf.constant([0, 0, 10.0]) # 7,3,5.0
	camera_lookat = tf.constant([0,0,0.0])
	camera_up = tf.constant([0,1.0,0])
	light_positions = tf.tile(tf.reshape(tf.constant([1e5,1e5,1e5]),[1,1,3]),[batchsize,1,1])
	light_intensities = tf.tile(tf.reshape(tf.constant([1e5,1e5,1e5]),[1,1,3]),[batchsize,1,1])
	ambient_color = tf.tile(tf.reshape(tf.constant([1.0,1,1]),[1,3]),[batchsize, 1])

	img = mesh_renderer.mesh_renderer(
		vertices_world_space,
		tf.cast(facemodel.tri-1,tf.int32),
		normals_world_space,
		face_color,
		camera_position = camera_position,
		camera_lookat = camera_lookat,
		camera_up = camera_up,
		light_positions = light_positions,
		light_intensities = light_intensities,
		image_width = size[0],
		image_height = size[1],
		fov_y = 12.5936,
		ambient_color = ambient_color)

	return img
```

But get the rendered image somehow "cut" unexpectedly like below:

![vd102_crop](https://user-images.githubusercontent.com/19768696/69808166-eeedbd00-1221-11ea-90de-4e607abe3fa8.jpg)

![vd102_reconstruct](https://user-images.githubusercontent.com/19768696/69808161-eac19f80-1221-11ea-97ce-dbdb88cd5685.jpg)

I also found that if I set the camera position at (0,0, >10), I got:
![vd102_reconstruct_12](https://user-images.githubusercontent.com/19768696/69809238-50169000-1224-11ea-86be-3346d4014d31.jpg)

If at (0,0, 8), I got:
![vd102_reconstruct_10](https://user-images.githubusercontent.com/19768696/69809271-5c025200-1224-11ea-87f6-fd93d55ebe4c.jpg)

Which is something nearly exact what I need, but just get bigger

What did I missed ?

**Comment by YuDeng** [comment]
Hi, you could try to modify certain parameters in the mesh_renderer function provided by tf_mesh_renderer which defines the near_clip and far_clip of the render_image. In default the far_clip is set to 10 so anything further than 10 will not be rendered. In my experiment, I set it to 50 so it will not influence the rendering process. Thanks.

**Comment by MengXinChengXuYuan** [comment]
Many thanks ....
This "bug" tortured me for a quite while :d

**Comment by hangon666** [comment]
@MengXinChengXuYuan 
Hello, the ouput img is a 4-D float32 tensor, how can I tranform it to the rendered image?
