### ISSUE TITLE
Warp  texture from input image

### ISSUE THREAD

**Issue by hungsing92** [microsoft/Deep3DFaceReconstruction#54]
Hi,

Sorry to disturb you again.

I want to warp the texture from input image, but when the face is not front, the invisible area will get the wrong color. Do you have any suggestion? I want to use the face symmetry to solve this problem. Do you know how to get the symmetry relations of the vertices? 

Thx!

**Comment by YuDeng** [comment]
You can turn to Nonlinear Morphable Model for some advice.  In their cvpr18 paper(https://github.com/tranluan/Nonlinear_Face_3DMM), they also use a symmetry constrain for face texture.

**Comment by hungsing92** [comment]
Thanks for your quick reply!

I found the symmetry relations from the origin BFM model (face05_symlist.txt).
