### ISSUE TITLE
Will you release the trained model for estimating skin probability?

### ISSUE THREAD

**Issue by fairytu** [microsoft/Deep3DFaceReconstruction#59]
Hi:
Thanks for your contribution.
I am intreasted in estimating skin probablity map. Will you release the trained model for estimating skin probability? 

If not convenient, is there any way to get the skin image dataset? I have tried to contact the   author of the dataset, but the provided email no longer exists.

**Comment by YuDeng** [comment]
I code for getting skin mask is now released.
