### ISSUE TITLE
Alignment of meshes to output images

### ISSUE THREAD

**Issue by jasamont** [microsoft/Deep3DFaceReconstruction#6]
How to get the alignment between generated meshes and output images as described in the readme?

**Comment by YuDeng** [comment]
Hi, in line 60 of demo.py, the _Reconstruction_ function outputs face_projection and z_buffer which are aligned with output image (224*224).  You can do rasterization with these outcomes to get a reconstruction image like those in readme. Note that face_projection's origin is lower-left corner while the image's origin is  upper-left corner.

**Comment by jasamont** [comment]
Hi, thank you for the answer. The code for rasterization isn't included in the repository, right?

**Comment by YuDeng** [comment]
No it has not been included yet. Sorry for that.

**Comment by albertpumarola** [comment]
It would be super useful if you could add it.

**Comment by Heershah4337** [comment]
> Hi, thank you for the answer. The code for rasterization isn't included in the repository, right?
Did you find the code for rasterization?

**Comment by Heershah4337** [comment]
> Hi, thank you for the answer. The code for rasterization isn't included in the repository, right?

Did you find the code for rasterization?

**Comment by jasamont** [comment]
> > Hi, thank you for the answer. The code for rasterization isn't included in the repository, right?
> 
> Did you find the code for rasterization?

Sadly no :/ The rasterization still not included? Its been over a year since i've looked at this code...

**Comment by YuDeng** [comment]
The rasterization and training process are now included.
