### ISSUE TITLE
The results of examples in the ./input subfolder are very bad.

### ISSUE THREAD

**Issue by fitzhu** [microsoft/Deep3DFaceReconstruction#64]
Hi, Yu:
 I follow the .md file and run demo.py, but the results are very bad. Are there any details I have missed?

![Snipaste_2020-03-02_16-32-22](https://user-images.githubusercontent.com/10624964/75658538-7aed0600-5ca3-11ea-863c-2d81fed58fa0.png)
![Snipaste_2020-03-02_16-32-33](https://user-images.githubusercontent.com/10624964/75658542-7b859c80-5ca3-11ea-9b43-1dc92bf46c28.png)

The image on the left is the input, right is output mesh.

**Comment by YuDeng** [comment]
Hi. Our model may give inferior results on some special cases,  such as faces with eyes closed or faces that are very close to the camera.
