### ISSUE TITLE
Region on FaceWarehouse for evaluation

### ISSUE THREAD

**Issue by Jim61C** [microsoft/Deep3DFaceReconstruction#65]
Hi!

I am wondering if you could share the vertex indices for the small and large region that you used for evaluation on FaceWarehouse?

Thanks!

**Comment by YuDeng** [comment]
Hi, here is the region we use for evaluating the facewarehouse. Note that the mesh vertex is re-distributed according to the evaluation protocol of MoFA (https://arxiv.org/abs/1703.10580)

**Comment by Jim61C** [comment]
Hi!

Thank you for sharing the regions!

I see. May I ask does it mean that the mesh topology in the original FaceWarehouse(11510 vertices, 22800 faces) have been redistributed to the topology defined in the .obj file that you attached here? If that is the case, I am wondering if you can share the redistributed face meshes or the tool to redistribute the mesh? 

Thanks!

**Comment by YuDeng** [comment]
> Hi!
> Thank you for sharing the regions!
> I get it now. So the shared region is out of the Bazel face model and you are taking a sub-region of the predicted 3D mesh not on the ground truth 3D mesh.
> In this case, would you mind sharing just the list of those 180 meshes (9 identities, 20 expressions each) used for evaluation on the FaceWareHouse dataset?
> Also, as it is mentioned that the FaceWareHouse mesh has been subdivided for a denser topology. Would you kindly share the densified 3D meshes used for evaluation or the tool used to densify the FaceWarehouse mesh?
> Thanks!

If I understand correctly about "the list of 180 meshes" you want, we use subject 4,136,138,145,146,147,148,149,150 out of the 150 subjects for evaluation, each with first 20 expressions. 
You can find the code for densification here https://drive.google.com/file/d/1Zcg0t7WZU8SMgv4gSaal-DGjNRYVubcP/view?usp=sharing

**Comment by Jim61C** [comment]
Yes! Those indexes are the exactly the ones I am looking for! Thank you for sharing!

**Comment by yangjituan** [comment]
@

> Yes! Those indexes are the exactly the ones I am looking for! Thank you for sharing!

Hi! 
i would like to know the mapping relations between the mesh vertex and the FaceWareHouse mesh?
could you help me with it .
