### ISSUE TITLE
ModuleNotFoundError: No module named 'mesh_renderer'

### ISSUE THREAD

**Issue by Sina-Abdous** [microsoft/Deep3DFaceReconstruction#69]
hi
i was encountered with a ModuleNotFoundError when i tried to to run demo.py for the first time .Does any body have any idea about that?
![Annotation 2020-04-10 113216](https://user-images.githubusercontent.com/40735839/78970632-023d5d00-7b1f-11ea-9d69-985aa8f8eb44.png)

**Comment by YuDeng** [comment]
Hi, you should first install tf_mesh_renderer via pip install mesh_renderer as described in the system requirements part.

**Comment by Sina-Abdous** [comment]
Thanks for your response
