### ISSUE TITLE
Any plan to release the training code?

### ISSUE THREAD

**Issue by qiaone** [microsoft/Deep3DFaceReconstruction#7]

**Comment by YuDeng** [comment]
Hi.  Training code is not available recently because part of our model (face recognition network) is not publicly available. We are still working on organizing the training code. Sorry for the inconvenience.

**Comment by qiaone** [comment]
> Hi. Training code is not available recently because part of our model (face recognition network) is not publicly available. We are still working on organizing the training code. Sorry for the inconvenience.

Thanks for sharing your code.

**Comment by Ivy147** [comment]
waiting for your training code

**Comment by Oktai15** [comment]
What about training code, @YuDeng?

**Comment by YokkaBear** [comment]
Looking forward to your training code @YuDeng

**Comment by YuDeng** [comment]
Training code for single image reconstruction is available now.
