### ISSUE TITLE
not able to find the morphable.mat file and BFM_model_front.mat in the BFM MODEL SITE

### ISSUE THREAD

**Issue by Vamshigoud784** [microsoft/Deep3DFaceReconstruction#78]
Hi as you have said in instructions,
i have received a email containing the h5 files link but i was not able to find the  BFM_model_front.mat as you have mentioned. please can you add some link where can i get those files . please help needed. Thanks[  ]
_

**Comment by YuDeng** [comment]
If you get access to the basel face model 2009, they should provide you a link to download their original model, which contains a file named 01_MorphableModel.mat. Then you can run demo.py and BFM_model_front.mat will be generated automatically.

**Comment by Vamshigoud784** [comment]
> BFM_model_front

Hi Yu,
Thanks for the fast response i got the 01_MorphableModel.mat File and i have run demo.py but it's not generationg the  BFM_model_front.mat  automatically. is there something i'm doing wrong?
Please have a look at this. Thanks for the reply
![Screenshot from 2020-06-01 12-34-59](https://user-images.githubusercontent.com/52398063/83384380-c8912000-a404-11ea-8a07-1b854a8ef5ec.png)
![Screenshot from 2020-06-01 12-35-41](https://user-images.githubusercontent.com/52398063/83384422-de064a00-a404-11ea-9954-54594e6ca970.png)
![Screenshot from 2020-06-01 12-38-39](https://user-images.githubusercontent.com/52398063/83384430-e2cafe00-a404-11ea-96d9-3181c08cf44b.png)

**Comment by YuDeng** [comment]
Hi, the code should check if BFM_model_front.mat exists in line 31, 32 in demo.py. If the file doesn't exist, demo.py should load transferBFM09 function to create the required .mat file. Can you check if these two lines have actually run?

**Comment by Vamshigoud784** [comment]
> Hi, the code should check if BFM_model_front.mat exists in line 31, 32 in demo.py. If the file doesn't exist, demo.py should load transferBFM09 function to create the required .mat file. Can you check if these two lines have actually run?

Hi Yu,
![Screenshot from 2020-06-01 13-05-29](https://user-images.githubusercontent.com/52398063/83386455-bd3ff380-a408-11ea-9eeb-2c624a268e9c.png)Hi, the code should check if BFM_model_front.mat exists in line 31, 32 in demo.py. If the file doesn't exist, demo.py should load transferBFM09 function to create the required .mat file. Can you check if these two lines have actually run?
 it is running now but the other issue is it is showing axis error . please have a look at it.
thank you

**Comment by Vamshigoud784** [comment]
> Hi, the code should check if BFM_model_front.mat exists in line 31, 32 in demo.py. If the file doesn't exist, demo.py should load transferBFM09 function to create the required .mat file. Can you check if these two lines have actually run?

Hi i was able to run the code now but the error keeps coming please have a look at it.
thanks for amazing response.
![Uploading Screenshot from 2020-06-01 13-05-29.png…]()

**Comment by YuDeng** [comment]
What version of tensorflow are you using? The error seems to be caused by an incompatible version. I suggest using tensorflow 1.12 or lower version to run the code.

**Comment by Vamshigoud784** [comment]
> What version of tensorflow are you using? The error seems to be caused by an incompatible version. I suggest using tensorflow 1.12 or lower version to run the code.

Thanks i have downgraded tensorflow now . i have another issue now. i have posted my dependencies too please let me know if any of it is wrong?
![Screenshot from 2020-06-01 13-21-08](https://user-images.githubusercontent.com/52398063/83387751-e8c3dd80-a40a-11ea-8ba1-4db23816ef64.png)
![Screenshot from 2020-06-01 13-20-37](https://user-images.githubusercontent.com/52398063/83387763-eeb9be80-a40a-11ea-8358-3d8187ab85fe.png)

**Comment by YuDeng** [comment]
This is caused by tf_mesh_renderer library. The tf_mesh_renderer lib will compile using corresponding tensorflow version. If you install tf_mesh_renderer first and then change the tf version, it can also cause an incompatible error. In this case, you can uninstall tf_mesh_renderer then install it again.

**Comment by Vamshigoud784** [comment]
Hi Yu,
Thanks. it is working now but how can i get texture for the obj file . but how can i get texture file or material file . for the face colour  . i have mat file how can i export to import the colours on mesh obj
![mesh](https://user-images.githubusercontent.com/52398063/83396996-8a9ef680-a41a-11ea-9a6f-f104e3326574.png)

**Comment by YuDeng** [comment]
The face color information is recorded in each vertex. You can use Mashlab to view it. I am not so sure how to view them in Blender. You may need to transfer it to the format you need.

**Comment by Vamshigoud784** [comment]
> The face color information is recorded in each vertex in .obj file. You can use Mashlab to view it. I am not so sure how to view them in Blender. You may need to transfer it to the format you need.


Hi this is the output i got. its so real but i noticed that all output obj have same colour eyes and i cannot see the lip colour in this? is there something i'm missing like i have seen one of these issues will uv_mat will help in adding more colours to face?
![gigi2](https://user-images.githubusercontent.com/52398063/83409264-b5e11000-a431-11ea-99ad-91c7ec785056.jpg)
![meshs](https://user-images.githubusercontent.com/52398063/83409280-be394b00-a431-11ea-9253-d0163f2c32b0.png)

**Comment by YuDeng** [comment]
Colors of eyes and lips may not be reconstructed faithfully due to the ability of BFM itself. The color of a face is totally depicted by a texture vector instead of directly copied from the input image.  To obtain better color, mixing the current result with color extracted from the input image can be a good choice.
