### ISSUE TITLE
What is the output of pre-trained model?

### ISSUE THREAD

**Issue by asterisk37n** [microsoft/Deep3DFaceReconstruction#80]
Thank you, Yu for uploading pre-trained model. Uploaded model gets input image shaped in [1, 224, 224, 3] and outputs coefficient of [1, 258] for something. What is this 258 dimension coefficients for? I can see fc-id, fc-ex, fc-tex and some other coefficients of 3DMM model on tensorboard (Figure below). I expected those 3DMM coefficients lead to reconstructed image and losses, not another coefficients for something. Thank you. I welcome any comments.

![Screenshot from 2020-06-16 17-02-25](https://user-images.githubusercontent.com/16299750/84749013-620b2500-aff4-11ea-8f58-4586ed141fe6.png)

**Comment by YuDeng** [comment]
In my later experiments, this dimension is used to predict the focal length of an image. It is useless here. It should be a mistake that I include this dimension in the final output.  The first 257 dimensions are identity(80), expression(64), texture(80), pose angles(3), lighting parameters(27), translation(3). The first 257 dimension output is the same as the variable "coeff" in line 48 in demo.py. This coeff is then sent to an analytic image formation process to obtain a reconstructed image.

**Comment by asterisk37n** [comment]
@YuDeng 
Thank you for explanation. Now everything is clear 🎉
