### ISSUE TITLE
Need Less vertices

### ISSUE THREAD

**Issue by t-qureshi** [microsoft/Deep3DFaceReconstruction#81]
Hi, thanks for sharing this very great work. I have implemented this repo and results are very great. 
But now, i just want to get .obj with less vertices. currently, by default we are getting 35709. But how we can get less.

**Comment by YuDeng** [comment]
Hi, you can first use tools like MeshLab which allows you to delete any face vertex.  Then by comparing the modified face mesh with the original one, you can get the index of preserved vertex. Finally you can use the index to get new face mesh with less vertices.

**Comment by xingmimfl** [comment]
> Hi, thanks for sharing this very great work. I have implemented this repo and results are very great.
> But now, i just want to get .obj with less vertices. currently, by default we are getting 35709. But how we can get less.

hello，could you send a code to me? I also re-implemented this repo, but results are not very good, and you can see the results in my repo.  my email is 506576511@qq.com, thx
