### ISSUE TITLE
2D Landmark matching problem

### ISSUE THREAD

**Issue by fanfanda** [microsoft/Deep3DFaceReconstruction#82]
Nice work! Thanks for your source code! However, I am confused in the following two points.
1). I randomly generated faces from your model and used Compute_landmark and Projection_block function generates the corresponding 2D face key point coordinates. But I found that there is a big gap between the coordinates generated by yours (function Projection_block) and library [face_alignment](https://github.com/1adrianb/face-alignment). Is this normal? Is this due to the inaccurate keypoints selected in the 3D model?
eg.: your result (first 10 points): `[[ 63.8120, 102.0407],
        [ 64.6816, 119.7306],
        [ 67.2531, 136.0472],
        [ 68.9704, 150.4634],
        [ 71.0780, 166.1672],
        [ 74.8879, 178.4916],
        [ 79.8947, 185.2664],
        [ 88.5861, 190.6918],
        [107.3693, 193.8777],
        [131.0653, 188.0488]]`
 Generated by [face_alignment](https://github.com/1adrianb/face-alignment):  `[[ 56.,  93.],
       [ 54., 108.],
       [ 56., 123.],
       [ 61., 141.],
       [ 66., 161.],
       [ 74., 174.],
       [ 84., 181.],
       [ 89., 189.],
       [109., 191.],
       [132., 186.]]`

2). I'm reproducing your paper. I want to ask if the output of the last layer of R-Net has an activation layer, because I found that some of the output coefficients are non negative, some are positive and negative. (This may be a stupid question, because you've given the TF model file, but I'm not sure I can parse out the network structure.)

Hope your reply, thank you!

**Comment by YuDeng** [comment]
Hi, could you post some results in the figures? Then it is clearer to see the differences between our results and theirs.

For the second question, we do not use any activation for the final layer of R-Net. The final layer only contains linear multiplications.

**Comment by fanfanda** [comment]
Thanks for your reply!
I found that the mismatch was probably due to the face_alignment.LandmarksType._2D I used. Because in your code, the key face points are mapped back to 2D images through 3DMM, so I should use the face_alignment.LandmarksType._3D parameter in facealignment. However, I did not find that how to convert the 3D result to the 2D image pixel locations, can you share this part of your code (preprocess the input image and get the 2D landmark)? Am I right?

**Comment by fanfanda** [comment]
Your results:
![test1](https://user-images.githubusercontent.com/25380176/87141538-c197e000-c2d5-11ea-9124-c3d26bde5404.png)
face_alignment.LandmarksType._2D results:
![test2](https://user-images.githubusercontent.com/25380176/87141568-cfe5fc00-c2d5-11ea-9b57-e92335f3e378.png)

**Comment by YuDeng** [comment]
Hi, can you try to discard the z dimension of the face_alignment.LandmarksType._3D result? I think it will give you the landmark results on 2D image.

**Comment by fanfanda** [comment]
Thanks, I will try it~
