### ISSUE TITLE
Reconstruct images with higher resolution?

### ISSUE THREAD

**Issue by Timmate** [microsoft/Deep3DFaceReconstruction#83]
Hi, thank you a lot for sharing this project! I would like to align a reconstructed image with the original one whose resolution is 512x512, so I thought I could modify the code to make it output reconstructed images with some desirable higher resolution (e.g. 512x512). However, I've tried changing the hard-coded number 224 and also numbers related to it (like 112 or 223) in the scripts `demo.py`, `face_decoder.py` and `preprocess_img.py`, but it didn't help and the results I got look pretty ugly. Could you point out what I have done wrong? Thank you!

**Comment by alter-sachin** [comment]
Were you able to resolve this?

**Comment by YuDeng** [comment]
Sorry for the late response.  If you want to render image with higher resolution, instead of change the parameters associated with image resolution, you also have to change the fov_y in the rendering phase from 2xtf.atan(112/(1015.))x180./m.pi to 2xtf.atan(half_your_resolution/(1015.))x180./m.pi. Tell me if this solves your problem.

**Comment by Timmate** [comment]
@alter-sachin, @YuDeng, I am really sorry for the late reply, unfortunately, I did not receive any notifications about new replies in this issue thread. @YuDeng, I have tried your approach and, for some reason, it does not work out for me as I still keep getting some ugly faces (please do not try this to avoid nightmares) as an output. However, I found a workaround to this issue which, in fact, is not really about actual rendering a reconstructed image with higher resolution, rather about "uncropping" and rescaling (resizing) a reconstructed image back to the resolution of an original image. 

Here is the [link][1] to a gist with the script implementing this workaround. Basically, this script is a modified version of the `demo.py` which processes all images in the `input` directory and saves rescaled masks in the `rescaled_masks` directory. Please note that in this code a reconstructed image is called a "mask" or "scaled and cropped mask" (due to the fact that it is indeed scaled and cropped compared to the original image) and, for the sake of shortness, in some lines an uncropped and rescaled mask is called just a "rescaled mask". The "uncropping" and rescaling are performed using the transformation parameters returned by the `Preprocess()` function in the "downscaling" phase, i.e., when the original image is resized and cropped to the size of 224x244 before the rendering phase.

Again, this solution is not really about rendering a high-resolution output, rather about taking a 224x224 mask (i.e., a reconstructed image) and just rescaling it back to the resolution of the original image. However, I hope that this approach still might be useful in some cases. Also, please let me know if you find any issues/problems with this code.

[1]: https://gist.github.com/Timmate/cc089034dac3f9fbbdcbb889aa2aaa0d

**Comment by Timmate** [comment]
The results look like this:
![000002](https://user-images.githubusercontent.com/17045930/89653380-3ce5b500-d8c7-11ea-9b34-5658bd1d83fa.jpg)
![000002_rec](https://user-images.githubusercontent.com/17045930/89653377-3c4d1e80-d8c7-11ea-9ac7-a87252ba9730.jpg)
![015270](https://user-images.githubusercontent.com/17045930/89653382-3d7e4b80-d8c7-11ea-89be-966c2799a98e.jpg)
![015270_rec](https://user-images.githubusercontent.com/17045930/89653381-3ce5b500-d8c7-11ea-925a-25c5bf7b3d02.jpg)

**Comment by Timmate** [comment]
I think I can close this issue as my problem was solved.
