### ISSUE TITLE
Input image and txt file explanation .. Whats in .txt ?

### ISSUE THREAD

**Issue by SIGMIND** [microsoft/Deep3DFaceReconstruction#85]
I have found some sample images and corresponding .txt files. What I see inside is 5 rows of numbers. Is it 5 point landmarks? If so, why does the landmarks differs from original to the ones found from the resultant mat file? Also, it differs from dlib 5 point landmark detection as well. Please need some explanation.

**Comment by YuDeng** [comment]
The .txt file contains 5 landmarks of the original input image including right eye, left eye, nose tip, right mouth corner and left mouth corner. We use our private landmark detector to get these results so it might be different from dlib result. While the 5 landmarks in the result .mat file corresponding to 224x224 cropped image sent to the reconstruction network.

**Comment by SIGMIND** [comment]
Thanks for the explanation. I want to test with a custom image so need to know how to generate this .txt file for my image

**Comment by ZJH2233** [comment]
If you test a handful of images , write a txt by ourself. For example,i will open the my image in PhotoShop and record xy coordinates of 5 landmarks . The last,new a txt write the coordinates.

**Comment by phillipdp** [comment]
Good afternoon,

Thank you so much for your feedback on this - I have built my .txt files according to the coordinates needed but I am still recievng errors on my input files...whereas the demo files are working perfectly, so it's definitely me doing something wrong.

Please could I ask for some more information around the formatting of the txt file:

1. Is the order explicitely right eye, left eye, nose tip, right mouth, left mouth? I have worked out the coordinates to be left eye/right eye/nose tip/left mouth/right mouth? Perhaps I'm doing that very wrong?
2. The space inbetween the coordinates - is this a tab space?
3. is the end-of-line '\r\n'?

I appreciate any feedback in advance :)

**Comment by ZJH2233** [comment]
@phillipdp
Maybe the problem not your txt.
But about the question 1.

> Is the order explicitely **right eye, left eye, nose tip, right mouth, left mouth**? I have worked out the coordinates to be **left eye/right eye/nose tip/left mouth/right mouth**? Perhaps I'm doing that very wrong?
The space inbetween the coordinates - is this a tab space?

Maybe you just typed it wrong，the second order “left eye/right eye/nose tip/left mouth/right mouth“ is true.

> ValueError: Cannot feed value of shape (1, 224, 224, 4) for Tensor 'input_imgs:0', which has shape '(1, 224, 224, 3)

This means that the images your input was wrong.Sorry i don't know 'mime type'.It could be a picture format error.A normal images such as take pictures with your phone,you will get a normal RGB image.The image size was (x,y,3).The number 3 on behalf of the RGB.x,y represents the height and width of the image
And when you input this image to this project.It will automatic processing to a crop image(1,224,224,3).The number 1 on behalf of the batchsize and is a  fixed value.

So,you input a image with 'mime type'.It could be a picture format error.Such as  the 'mime type' size is (x,y,4).So,project automatic processing to a crop image(1,224,224,4).Last,get error

> ValueError: Cannot feed value of shape (1, 224, 224, 4) for Tensor 'input_imgs:0', which has shape '(1, 224, 224, 3)
(translation:I need a image of shape (1, 224, 224, 3),but you give me a shape (1, 224, 224, 4).)

**Comment by CaptainStabs** [comment]
You can also use MTCNN using the following code.
Just make sure that the script is in the same directory as the image.
The text file requires only the coordinates, so delete the keys and commas.

`from mtcnn import MTCNN
import cv2

img2 = input("Image: ")
img = cv2.cvtColor(cv2.imread(img2), cv2.COLOR_BGR2RGB)
detector = MTCNN()
print(detector.detect_faces(img))`
