### ISSUE TITLE
Training code

### ISSUE THREAD

**Issue by HOMGH** [microsoft/Deep3DFaceReconstruction#86]
Hi,
Thanks for sharing your source code. Would you please share your training code as well?

**Comment by WonwoongCho** [comment]
I also appreciate your every effort for sharing the project. By the way, to fully understand your research project beyond the published paper, I would love to have an opportunity to read your training code. Would you care to open the training code?

**Comment by YuDeng** [comment]
Training code for single image reconstruction available now.

**Comment by HOMGH** [comment]
> Training code for single image reconstruction available now.

Thank you so much for sharing your complete code. Would you please provide the codes you used for quantitative evaluations (shape errors in mm)? Thanks.
