### ISSUE TITLE
don't work well for chinese?

### ISSUE THREAD

**Issue by vastyao** [microsoft/Deep3DFaceReconstruction#9]
Hi, I have a question when I try this work. whether does it not work well for Chinese? The result don't like the person who is a Chinese which I input .

**Comment by YuDeng** [comment]
The model may not perform well on Chinese people because of two reasons. First one is that the face model we use (BFM09) are build mainly with Caucasian. Second one is that images used to train our reconstruction network are lack of Asian people.

**Comment by vastyao** [comment]
ok, I get it. Thank you very much.
