### ISSUE TITLE
about evaluating on AFLW2000-3D

### ISSUE THREAD

**Issue by hao-qiang** [microsoft/Deep3DFaceReconstruction#99]
hi,
Great work. You method need alignment the input according to 5 3d landmarks before inference, when evaluating on AFLW2000-3D, which landmarks detector do you use, or just use 5 landmarks from ground truth.
Thanks.

**Comment by YuDeng** [comment]
Hi, for this evaluation, we use an in-house landmark detector to generate 5 landmarks for alignment.
